Makefile

go get -u <package> does an update of the go.mod and go.sum files; go
install <package> installs the binary at that location.
It seems the intent of this line in the makefile is to install swag if it
doesn't exist based on the ||, so let's actually install it, instead of
just updating the local deps.
This also has the advantage of not immediately generating a diff when
someone doesn't have swag installed.
Signed-off-by: Tycho Andersen <tycho@tycho.ws>

install swag instead of updating it in the go deps

---

.bazel/golangcilint.yaml
Makefile
pkg/api/config.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/api/errors.go
pkg/api/ldap.go
pkg/api/routes.go
pkg/cli/root.go
pkg/cli/root_test.go
pkg/compliance/v1_0_0/check_test.go
pkg/log/log.go
pkg/storage/storage.go
pkg/storage/storage_test.go

Using go 1.13.5 caused golangci-lint to break.
Upgrading to 1.21.0 introduced lots of new lint findings.
Fixed everything except I add ignores for the following lint rules:
disable: funlen,godox,gocognit

Issue 42 - Fixing issues with upgrading to golangci-lint 1.21.0

---

pkg/api/routes.go
pkg/compliance/v1_0_0/check.go

"mount blob" was the only feature we didn't handle.
We don't fully support it yet because we don't have access control
support, but at least handle it and return something sane to remain
compliant.

routes: handle "mount blob" to remain compliant

---

pkg/api/routes.go

once we have an non-EOF error in this path, not clear if we can really
recover.

routes: be more paranoid

---

pkg/api/routes.go
pkg/log/log.go

There still appears to be another path where we are seeing 500s.
Adding more logs to catch this path.

routes: add more logs

---

go.mod
go.sum

older versions of json-iterator appear to have an issue with maps

go.mod: update json-iterator

---

examples/config-test.json
pkg/api/regexp.go
pkg/api/routes.go
pkg/compliance/v1_0_0/check.go
pkg/storage/storage.go

dist-spec compliance tests are now becoming a part of dist-spec repo
itself - we want to be compliant
pkg/api/regex.go:
* revert uppercasing in repository names
pkg/api/routes.go:
* ListTags() should support the URL params 'n' and 'last'
for pagination
* s/uuid/session_id/g to use the dist-spec's naming
* Fix off-by-one error in GetBlobUpload()'s http response "Range" header
* DeleteManifest() success status code is 202
* Fix PatchBlobUpload() to account for "streamed" use case
where neither "Content-Length" nor "Content-Range" headers are set
pkg/storage/storage.go:
* Add a "streamed" version of PutBlobChunk() called PutBlobChunkStreamed()
pkg/compliance/v1_0_0/check.go:
* fix unit tests to account for changed response status codes

compliance: be compliant with dist-spec compliance tests

---

pkg/compliance/v1_0_0/check.go
pkg/storage/storage.go
pkg/storage/storage_test.go

Fixes issue #67.
As per dist spec, DELETE of a image manifest can only be done with
digest as <reference> param. Previously, tags were being allowed as
well. This is not conformant to the spec.

manifest can be deleted only by digest and not tag

---

Makefile
pkg/api/routes.go
pkg/compliance/v1_0_0/check.go

Previously, CheckManifest() was not checking for repo not found
condition and would default to 500 status code.
Add the check now to return 404.
Fixes issue #74

routes: CheckManifest should return 404 when repo is unknown

---

pkg/api/routes.go
pkg/compliance/v1_0_0/check.go

Previously returning 404s as failure code, dist-spec says 400s.

conformance: fix http status codes for MANIFEST DELETE failures.

---

README.md
WORKSPACE
errors/errors.go
go.mod
go.sum
pkg/api/controller.go
pkg/api/routes.go
pkg/compliance/v1_0_0/check.go
pkg/storage/BUILD.bazel
pkg/storage/cache.go
pkg/storage/cache_test.go
pkg/storage/storage.go
pkg/storage/storage_test.go

As the number of repos and layers increases, the greater the probability
that layers are duplicated. We dedupe using hard links when content is
the same. This is intended to be purely a storage layer optimization.
Access control when available is orthogonal this optimization.
Also, note that we designed dedupe to make slow and steady progress in the
background so that zot can continue to serve layers/images while dedupe
is happening.
Add a durable cache to help speed up layer lookups.

dedupe: use hard links to dedupe blobs

---

pkg/api/controller_test.go
pkg/api/routes.go

header
containers/image is the dominant client library to interact with
registries.
It detects which authentication to use based on the WWW-Authenticate
header returned when pinging "/v2/" end-point. If we didn't return this
header, then creds are not used for other write-protected end-points.
Hence, the compatibility fix.

compat: when in "world-readable" mode, return the WWW-Authenticate

---

README.md
pkg/api/routes.go
pkg/compliance/v1_0_0/check.go

OCI registries are moving towards a more generic artifact storage
mechanism. In short-term, at the very least support helm charts.

helm: relax Content-Type checks

---

pkg/storage/cache.go
pkg/storage/cache_test.go
pkg/storage/storage.go

In a production use case we found that the actual rootdir can be moved.
Currently, cache entries for dedupe record the full blob path which
doesn't work in the move use case.
Only for dedupe cache entries, record relative blob paths.

dedupe: record relative path for cache entries

---

.gitignore
pkg/api/auth.go
pkg/api/controller_test.go

earlier, when you had more than one creds in htpasswd file separated by newline, it used to only read the first cred in the file and ignore the rest.

fix: the bug when htpasswd has multiple creds

---

WORKSPACE
go.mod
go.sum
pkg/api/BUILD.bazel
pkg/storage/BUILD.bazel
pkg/storage/storage.go

We perform inline garbage collection of orphan blobs. However, the
dist-spec poses a problem because blobs begin their life as orphan blobs
and then a manifest is add which refers to these blobs.
We use umoci's GC() to perform garbage collection and policy support
has been added recently which can control whether a blob can be skipped
for GC.
In this patch, we use a time-based policy to skip blobs.

gc: add a policy to skip garbage collecting new blobs

---

pkg/api/auth.go
pkg/api/config.go
pkg/api/controller_test.go

This is useful if we want to roll out experimental versions of zot
pointing to some storage shared with another zot instance.
Also, when under storage full conditions, will be useful to turn on this
flag to prevent further writes.

auth: support a read-only mode

---

cmd/zot/main.go
cmd/zot/main_test.go
pkg/cli/config_cmd.go
pkg/cli/config_cmd_test.go
pkg/cli/image_cmd.go
pkg/cli/image_cmd_test.go
pkg/cli/root.go
pkg/cli/root_test.go
pkg/cli/searcher.go

earlier, some of the client exclusive code was being run on zot server
instance too. That caused an error when server doesn't have env variables required by client.
This PR moves that code out of the way of server

cli: move client-only code out of the server flow

---

pkg/cli/client.go
pkg/cli/config_cmd.go
pkg/cli/image_cmd.go
pkg/cli/image_cmd_test.go
pkg/cli/searcher.go
pkg/cli/service.go

adds a property in config : "verify-tls". It allows user to make unsecured HTTPS connections by skipping TLS certificate verification
```console
$ zot config add local https://localhost:8080         
$ zot config local -l                       
url = http://localhost:8080
showspinner = true
verify-tls = true
$ zot config local verify-tls false
$ zot config local -l                       
url = https://localhost:8080
showspinner = true
verify-tls = false
```

cli: add option to ignore TLS verification

---

pkg/storage/storage.go

**Steps to reproduce this issue (locally):-** 
1. Upload an image on zot server.
2. Manually delete any image blobs. 
3. Try to upload same image with different name.
**Fix:-** 
Using "destRecord" as a path in DeleteBlob function instead of "dst". 
dstRecord :- blob path stored in cache.
dst :- blob path that is trying to be uploaded. 
Currently, if the actual blob on disk may have been removed by GC/delete, during syncing the cache dst is being passed to DeleteBlob function and retry section is being continuously called because DeleteBlob function never deletes dst path (doesn't exist in db), dstRecord should be passed into DeleteBlob function because dstRecord is actual blob path stored in db.
If dst and dstRecord path value is same then this issue will not be produced and DeleteBlob …

Dedupe fix

---

.travis.yml

During running of bazel build we have selected no progress option during bazel build and it does not print any console outputs, travis expects some console outputs during build and if nothing printed to console for some time it exits the whole process. 
Adding travis_wait option during running of bazel build command, this will print a message on console every minute for 20 minutes.

Enable wait option during travis ci build

---

pkg/cli/service.go

Changes CLI output to print CVEs with higher severity above the ones with lower severity
Closes #131

cli: group CVEs by severity

---

errors/errors.go
pkg/cli/cve_cmd_test.go
pkg/cli/service.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/resolver.go

If image does not have any fixed tags, empty list with no error should be returned

Fixes issue #132

---

pkg/cli/BUILD.bazel
pkg/cli/cve_cmd_test.go
pkg/extensions/search/BUILD.bazel
pkg/extensions/search/cve/BUILD.bazel
pkg/extensions/search/cve/cve.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/resolver.go

Previously only image validation was done for only first tag and assumed that all tags will have same image media type but this was wrong assumption, changed the logic to enable image validation specific to image tag.
Also added fix for issue #130, if image scanning not supported due to invalid media type adding that image as an infected image.

search/cve: exclude unsupported images from fixed-tag list.

---

.travis.yml
go.mod
pkg/api/BUILD.bazel
pkg/api/controller_test.go
pkg/api/routes.go
pkg/cli/cve_cmd_test.go
pkg/extensions/search/cve/cve_test.go
pkg/storage/storage.go

The storage layer is protected with read-write locks.
However, we may be holding the locks over unnecessarily large critical
sections.
The typical workflow is that a blob is first uploaded via a per-client
private session-id meaning the blob is not publicly visible yet. When
the blob being uploaded is very large, the transfer takes a long time
while holding the lock.
Private session-id based uploads don't really need locks, and hold locks
only when blobs are published after the upload is complete.
Note:- 
1. commit: "test: minimize trivy db download tests to avoid api rate limit" added to avoid api rate limit during build process.
2. Since I added multiple parallel request tests now, make test is taking longer time to execute and that's why we need to add wait during make process also in …

routes: refactor locks to handle large file uploads

---

.travis.yml
Makefile
Makefile.bazel
cmd/zot/BUILD.bazel
codecov.yml
pkg/api/BUILD.bazel
pkg/api/config.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/api/routes.go
pkg/cli/BUILD.bazel
pkg/cli/cli.go
pkg/cli/client.go
pkg/cli/config_cmd.go
pkg/cli/config_cmd_test.go
pkg/cli/cve_cmd.go
pkg/cli/cve_cmd_test.go
pkg/cli/image_cmd.go
pkg/cli/image_cmd_test.go
pkg/cli/minimal.go
pkg/cli/root.go
pkg/cli/searcher.go
pkg/cli/service.go
pkg/extensions/BUILD.bazel
pkg/extensions/config.go
pkg/extensions/extension.go
pkg/extensions/extensions.go
pkg/extensions/minimal.go
pkg/extensions/search/cve/BUILD.bazel
pkg/extensions/search/cve/cve_test.go

This PR is about creating a "zot-minimal" build target which only does dist-spec serving.
Added two build tags minimal and extended, minimal will create a binary that only serves dist-spec serving while extended will include CVE scan also.
Added one build rule (minimal-binary) also in Makefile, this rule will generate a minimal-binary while existing binary rule will now generate full binary.
Note:- 
**commit "build: increase wait timeout for travis bazel build process" bazel is taking more than 20 minutes to complete build process.**

customizable binaries

---

errors/errors.go
pkg/cli/config_cmd.go
pkg/cli/config_cmd_test.go

This PR should fix error:
```
$ zot config -l
$ zot config add main https://test-url.com
$ zot config -l
main    https://test-url.com
$ zot config add main https://test-url.com
$ zot config -l
main    https://test-url.com
main    https://test-url.com
```
Fix:
```
$ ./bin/zot config -l
$ ./bin/zot config add main https://test-url.com
$ ./bin/zot config -l
main    https://test-url.com
$ ./bin/zot config add main https://test-url.com
Error: config: config name is used. see 'zot config -l'
Usage:
zot config add <config-name> <url> [flags]
Flags:
-h, --help   help for add
Useful variables:
url           zot server URL
showspinner   show spinner while loading data [true/false]
verify-tls    verify TLS Certificate verification of the server [default: true]
```
closes: #150

Raise error when adding a new zot config with an existed saved name

---

.github/workflows/oci-conformance-action.yml

Previously conformance github action was failing because it was pointing to invalid branch of distribution-spec repo, changed github action to point it to correct one.

ci/cd: changed distrbution spec branch to main from master

---

pkg/api/controller_test.go
pkg/api/routes.go
pkg/extensions/search/cve/cve_test.go
pkg/storage/storage.go
pkg/storage/storage_test.go

In use cases, when there are large images with shared layers across
repositories, clients may benefit from not re-uploading the same blobs
over and over again.
We ensure this by hard linking when check-blob api is called.

dedupe: optimize check-blob with hard links

---

examples/config-example.json
examples/config-example.yaml
pkg/api/config.go
pkg/api/controller.go
pkg/log/log.go
pkg/log/log_test.go

The format in the zot-audit.log file:
```
{"level":"info","subject":"test","action":"POST","object":"/v2/test/centos/blobs/uploads/","status":202,"time":"2021-05-25T11:33:25.7515376+03:00","message":"HTTP API"}
```

logs: add an audit log for API calls

---

pkg/api/controller_test.go
pkg/api/routes.go
pkg/storage/storage.go
pkg/storage/storage_test.go

previously mount blob will look for blob that is provided in http request and try to hard link that path but ideally we should look for path from ourcache and do the hard link of that particular path, this commit does the same.

api: use blob cache path while making hard link

---

README.md
examples/README.md

We have built a long list of features and the documentation for users is
only available under examples/
Add a examples/README.md to further explain various configuration
options.

doc: add initial documentation for configuration options

---

pkg/api/authz.go
pkg/api/ldap.go
pkg/api/routes.go
pkg/log/log.go

Some LDAP servers are not MT-safe in that when searches happen with binds
in flight leads to errors such as:
"comment: No other operations may be performed on the connection while a
bind is outstanding"
Add goroutine-id in logs to help debug MT bugs.
Fixes issue #224

authn: serialize ldap authn calls

---

.github/workflows/ci-cd.yml
examples/README.md
examples/config-s3.json
go.mod
go.sum
pkg/api/config/config.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/cli/root.go
pkg/storage/s3/s3_test.go
pkg/storage/s3/storage.go
pkg/storage/storage.go
pkg/storage/storage_fs.go
pkg/storage/storage_fs_test.go
pkg/storage/storage_test.go

using: https://github.com/distribution/distribution/tree/main/registry/storage/driver
Supports a lot of storages types.

storage: add s3 backend support (without GC and dedupe)

---

examples/README.md
examples/config-sync.json
examples/sync-auth-filepath.json
pkg/api/controller.go
pkg/api/routes.go
pkg/cli/root.go
pkg/cli/root_test.go
pkg/extensions/extensions.go
pkg/extensions/minimal.go
pkg/extensions/sync/http_handler.go
pkg/extensions/sync/on_demand.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/extensions/sync/utils.go

Summary:
- fixed https://github.com/anuvu/zot/issues/266
- Added sync Readme
- Accept all images with or without signatures, for more details see: https://www.mankier.com/5/containers-policy.json, removed the need of /etc/containers/policy.json file
- Fixed sync switch statement in routes
- Fixed enabling sync with multiple storage subpaths.

sync: copy to a local cache first instead of writing over http

---

pkg/api/controller_test.go
pkg/cli/client.go
pkg/cli/client_test.go
pkg/cli/cve_cmd_test.go
pkg/cli/image_cmd_test.go
pkg/compliance/v1_0_0/check.go
pkg/compliance/v1_0_0/check_test.go
pkg/exporter/api/controller_test.go
pkg/extensions/search/common/common_test.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/digest/digest_test.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/log/log_test.go
pkg/storage/storage_fs.go
pkg/storage/storage_fs_test.go
pkg/storage/storage_test.go
test/common.go
test/common_test.go

Signed-off-by: Alexei Dodon <adodon@cisco.com>
Root cause: same port used by controller & shared across different tests that runs in parallel.

Fix data races in tests, closes #255

---

go.mod
go.sum

GHSA-77vh-xpmg-72qh
pull in upstream github.com/opencontainers/image-spec where this is
fixed.

go.mod: fix another dependabot alert

---

pkg/api/controller.go
pkg/api/routes.go
pkg/extensions/extensions.go
pkg/extensions/minimal.go
pkg/extensions/sync/on_demand.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go

Because after a server.Shutdown sync goroutine could be still running, let's use waitgroup to wait for a sync to either return an error or to finish 1 run, otherwise a data race on zerolog could happen.
TODO: add comments
run build multiple times

Fix race detected in sync test, closes #302

---

pkg/api/controller.go
pkg/api/controller_test.go
pkg/cli/root.go
pkg/cli/root_test.go
pkg/storage/scrub.go
pkg/storage/scrub_test.go

*  Adding "scrub" cli command and using umoci codebase as a library ( for "umoci stat" )
*  For the moment this command can be used only if the server is not running
*  Example of output for cli command:
```
$ bin/zot scrub examples/config-multiple.json  
IMAGE NAME                        TAG                       STATUS    ERROR         
postgres                          latest                    affected  stat: discard trailing "application/vnd.oci.image.config.v1+json" blob: expected sha256:c0616bde68243ffda5e0a535502d6173da5644562fd5560059a369ea6563793f not sha256:2dc11ae9a808dedf5a1cd8431231f6b0a5e47dbcd61e527a975a474421ddc0d8: verified reader digest mismatch  
a/busybox                         latest                    affected  blob: not found  
busybox …
```

Implement "scrub" to check manifest/blob integrity

---

examples/README.md
pkg/cli/root_test.go
pkg/extensions/extensions.go
pkg/extensions/sync/http_handler.go
pkg/extensions/sync/on_demand.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_test.go

Filtering out sync on demand images based on content configuration

Disable sync periodically polling when pollInterval is not configured

---

pkg/extensions/sync/sync.go

Fix negative WaitGroup counter at runtime

---

Makefile

bug fix
When running 'make test' the tests will fail if the user does not have notation tool installed.
We need a target that will check if notation is installed and if it is not- to install it before running the tests.
Failures:
* zotregistry.io/zot/pkg/api_test/controller_test.go 
Line 2971:
Expected: nil
Actual:   'exec: "notation": executable file not found in $PATH'
524 total assertions
--- FAIL: TestImageSignatures (4.50s)
'make test' passes regardless if you have notation tool installed or not
Not needed
**Will …

Install notation as prerequisite for test Makefile target

---

go.mod
go.sum
pkg/storage/storage_fs.go

performance enchancement
#306 
Uses the sha_ni extensions for CPUs that support it.

storage: use sha256-simd from minio

---

examples/metrics/Makefile
pkg/exporter/api/controller_test.go
pkg/exporter/api/exporter.go
pkg/extensions/monitoring/common.go
pkg/extensions/monitoring/extension.go
pkg/extensions/monitoring/minimal.go
pkg/storage/s3/storage.go
pkg/storage/scrub.go
pkg/storage/storage.go
pkg/storage/storage_fs.go
pkg/storage/storage_test.go

feature
#279 
We also want to track how long storage locks are being held so that we get better visibility into contention and latency.
```release-note
```

Added storage latency histogram metric closes #279

---

pkg/cli/root.go

Fix cli version showing help message, closes #361

---

pkg/cli/root_test.go
pkg/extensions/sync/on_demand.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/extensions/sync/utils.go
pkg/storage/cache_test.go

feature
#261 
Added support for syncing notary and cosign signatures
**Testing done on this change**: 
no
no
```release-note
```

sync: Added support for syncing notary/cosign signatures, closes #261

---

Makefile
cmd/zb/main.go
cmd/zb/main_test.go
cmd/zb/perf.go
codecov.yml

'make bench' produces a bin/zb binary
bin/zb --help
```release-note
```

perf: add a 'zb' binary for perf testing of dist-spec registries

---

.github/workflows/benchmark.yaml
Makefile
cmd/zb/main.go
cmd/zb/perf.go

feature
Adds a performance benchmark in ci/cd so we don't regress across commits.
```release-note
```

ci/cd: add continuous benchmark action

---

.github/workflows/benchmark.yaml

ci/cd: update continuous benchmark version

---

pkg/cli/root.go

bug
Scrub command fails/crashes because metrics server not defined (needed after we added storage lock latency metrics)
`
midgard@ubuntu:~/work/rchincha/zot$ bin/zot scrub examples/config-test.json 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x93baf5]
goroutine 1 [running]:
zotregistry.io/zot/pkg/extensions/monitoring.ObserveStorageLockLatency({0x0, 0x0}, 0x2eb726eb, {0xc0003d12b0, 0x8}, {0x1ed39e9, 0x5})
zotregistry.io/zot/pkg/extensions/monitoring/extension.go:196 +0xb5 …

Fix scrub command crash

---

README.md
examples/config-ratelimit.json
go.mod
go.sum
pkg/api/config/config.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/api/session.go

helps constraining resource usage and against flood attacks.
feature
#379 
Adds a global and per-method ratelimiter.

controller: support rate-limiting incoming requests

---

pkg/storage/storage_fs.go

cleanup/bug
#359 
```release-note
```

storage: return errors instead of panics

---

pkg/extensions/monitoring/common.go
pkg/extensions/monitoring/monitoring_test.go

Signed-off-by: Alexei Dodon <adodon@cisco.com>
bug
zot_repo_storage_bytes was disabled by mistake when we added new linter
Added tests to prevent this happening in the future.

bug: Storage used per zot repo metric is broken

---

.github/workflows/ci-cd.yml
Makefile
errors/errors.go
pkg/api/controller_test.go
pkg/api/routes.go
pkg/compliance/v1_0_0/check.go
pkg/test/dev.go
pkg/test/inject_test.go
pkg/test/prod.go

Feature
Provides a failure injection framework to inject and cover hard to reach code paths by artificially injecting failures.

coverage: add failure injection framework

---

pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/utils.go

Use InsecureSkipVerify only with https upstreams

---

examples/README.md
examples/config-sync.json
pkg/api/routes.go
pkg/cli/root.go
pkg/cli/root_test.go
pkg/common/common_test.go
pkg/extensions/extensions.go
pkg/extensions/minimal.go
pkg/extensions/sync/on_demand.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/extensions/sync/utils.go

sync: periodically retry if on-demand fails inline, closes #281

---

.github/workflows/ci-cd.yml

ci/cd bug
Whenever github workflows are changed, somehow PRs seem to keep the stale jobs. Adding a placeholder "deprecated" job to keep PRs happy.

ci/cd: restore part of github workflow for PRs

---

go.mod
pkg/extensions/search/common/common_test.go
pkg/extensions/search/common/oci_layout.go
pkg/extensions/search/generated.go
pkg/extensions/search/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/schema.graphql

- DetailedRepoInfo graphql api returns detailed repo info given name.
- Each repo contains its manifests info.
- Each manifest entry contains digest, signature, tag and layers info
- Each layer info containes digest, size.

search: graphql api to give detailed repo info

---

Dockerfile
Dockerfile-minimal
Dockerfile-zb
Dockerfile-zxp

ci/cd bug
Our docker files are two-stage and OS/ARCH args are not passed into the second stage, failing the binary copy.

ci/cd: fix image upload pipeline

---

go.sum

bug/cleanup
CVE-2022-23649: fix dependabot alert

remove linger go.sum entries to fix dependabot alert

---

pkg/api/controller_test.go
pkg/api/routes.go

fixes issue #442
bug
issue #442 
'from' query param is not support, so conform per spec.

conformance: fix cross-mount behavior when 'from' is missing

---

pkg/api/controller_test.go
pkg/cli/client_test.go
pkg/cli/cve_cmd_test.go
pkg/cli/image_cmd_test.go
pkg/cli/root_test.go
pkg/compliance/v1_0_0/check_test.go
pkg/exporter/api/controller_test.go
pkg/extensions/monitoring/monitoring_test.go
pkg/extensions/search/common/common_test.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/digest/digest_test.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/log/log_test.go
pkg/storage/cache_test.go
pkg/storage/scrub_test.go
pkg/storage/storage_fs_test.go
pkg/storage/storage_test.go
pkg/test/common_test.go

cleanup
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
This PR does not break upgrades or downgrades.
No.
**Does this PR introduce any user-facing …

test: use `T.TempDir` to create temporary test directory

---

pkg/api/authn.go
pkg/api/config/config.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/api/routes.go
pkg/extensions/extensions.go
pkg/extensions/search/cve/cve_test.go

whenever we make a request that contains header apart from CORS allowed header, browser sends a preflight request
and in response accept *Access-Control-Allow-Headers*.
preflight request is in form of OPTIONS method, added new http handler func to set headers
and returns HTTP status ok in case of OPTIONS method.
in case of authorization, request contains authorization header
added authorization header in Access-Control-Allow-Headers list
added AllowOrigin field in HTTPConfig this field value is set to Access-Control-Allow-Origin header and will give zot adminstrator to limit incoming request.

routes: changes required to do browser authentication

---

.github/workflows/cluster.yaml
README.md
examples/cluster/haproxy.cfg
test/cluster/config-minio.json

Added clustering github workflow

---

examples/config-allextensions.json
examples/config-bearer-auth.json
examples/config-commit.json
examples/config-conformance.json
examples/config-cve.json
examples/config-example.json
examples/config-gc.json
examples/config-metrics.json
examples/config-minimal.json
examples/config-multiple-cve.json
examples/config-multiple.json
examples/config-policy.json
examples/config-ratelimit.json
examples/config-s3.json
examples/config-sync.json
examples/config-test.json
examples/config-tls.json
go.mod
go.sum

https://github.com/project-zot/zot/security/dependabot/10
bug
Fix a dependabot alert triggered by distribution spec version in go.mod

fix dependabot alert

---

.github/workflows/ci-cd.yml

feature
Scan released images for vulnerabilities with trivy scanner

ci/cd: scan released images with trivy scanner

---

pkg/api/controller.go
pkg/cli/config_reloader.go
pkg/cli/config_reloader_test.go
pkg/cli/root.go
pkg/cli/root_test.go
pkg/extensions/extensions.go
pkg/extensions/minimal.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/extensions/sync/utils.go

sync: support reloading sync config when the config file changes

---

Makefile
test/blackbox/helpers.bash
test/blackbox/pushpull.bats

This is a follow up to #444.
cleanup
build
See #444, this PR migrates the tests in the makefile to the bats test framework.

Refactor the push/pull tests to use the bats test framework

---

Makefile
examples/config-bench.json
pkg/storage/storage_fs.go
pkg/storage/storage_fs_test.go

unit test
additional validation/coverage

gc: add a unit test

---

Dockerfile
Dockerfile-conformance
Dockerfile-minimal
Dockerfile-zb
Dockerfile-zxp
Makefile

build
Adds -buildmode=pie to build PIE binaries.

build: add -buildmode=pie to builds

---

pkg/extensions/sync/sync_test.go

sync: fix inconsistent test

---

examples/cluster/haproxy.cfg

Modified shared storage haproxy config to stick only writes, not reads
```release-note
```

Modified shared storage haproxy config to stick only writes, not reads

---

.github/workflows/ci-cd.yml
Makefile
pkg/cli/client_elevated_test.go
pkg/cli/client_test.go
pkg/storage/storage_fs_elevated_test.go
pkg/storage/storage_fs_test.go

cleanup
#459 
This PR separates the tests that need some sort of privileged execution from the ones that don't by use of new make targets.
This allows running without needing privileges or when they are not available.
Additionally, this PR will now make tests run on every platform (make test was only run on linux && amd64).

Separate make targets that require elevated privileges

---

.github/workflows/cluster.yaml
cmd/zb/helper.go
cmd/zb/main.go
cmd/zb/main_test.go
cmd/zb/perf.go

Add read-only tests, mixed read-only tests, mixed write-only tests and mixed read-write tests for zb binary

---

.github/workflows/ci-cd.yml
.github/workflows/oci-conformance-action.yml
examples/config-conformance.json
stacker-conformance.yaml
stacker-zb.yaml
stacker-zxp.yaml

Migrate from docker/build-push-action to stacker-build-push-action

---

examples/metrics/Dockerfile
examples/metrics/Dockerfile-minimal
examples/metrics/Dockerfile-zxp

After changing the name format of the binary(ex zot-$OS-$ARCH) trying to build images using metrics/Dockerfile doesn't work anymore because of name mismatch. This PR fixes this issue by updating the name of the binary to current format.
```release-note
```

update metrics/Dockerfile to match current binary name format

---

Makefile

this flag disables running additional tests after any test fails.

add failfast flag in go test

---

pkg/extensions/sync/on_demand.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/extensions/sync/utils.go

enhancement
#480 #479
This PR checks the existence of the blob before it being uploaded to the local imageStore, and only does so if it's not present.
Also, When syncing a repo with multiple images/tags, sync would create a local directory for each image, downloading the same blobs over and over again. This PR makes sync use the same folder per sync session, to massively reduce redownloading.

Reduce downloads by grouping .sync dirs for all images in the same repo

---

.github/workflows/ci-cd.yml

Signed-off-by: Catalin Hofnar <catalin.hofnar@gmail.com>
enhancement
This cuts down 45s-1m out of the Github build action by caching dependencies.

Changed Github workflow to cache dependencies

---

stacker-conformance.yaml
stacker-zb.yaml
stacker-zxp.yaml
stacker.yaml

Revert 058bbb94c68afbe3311e1c38bf094e5af7e79766
Use alpine:3
bug
stacker builds are broken in the final step since distroless and how we package using stacker are incompatible.
Final container image builds are broken.

build: fix base image in stacker files

---

examples/README.md
examples/config-s3.json
pkg/api/controller.go
pkg/api/controller_test.go
pkg/storage/cache.go
pkg/storage/cache_test.go
pkg/storage/s3/s3_test.go
pkg/storage/s3/storage.go
pkg/storage/storage_fs.go
pkg/storage/storage_test.go
test/cluster/config-minio.json

Because s3 doesn't support hard links we store duplicated blobs
as empty files. When the original blob is deleted its content is
moved to the the next duplicated blob and so on.
```release-note
```

s3: added logic for deduping blobs

---

pkg/api/constants/extensions.go
pkg/api/controller_test.go
pkg/extensions/_zot.md
pkg/extensions/extensions.go
pkg/extensions/search/search.md

distribution spec extension discover api has endpoints field required.
https://github.com/opencontainers/distribution-spec/blob/main/extensions/_oci.md#extensions-property-descriptions

add endpoints field in ext discover api

---

stacker-conformance.yaml
stacker.yaml

it is currently installed in the Makefile
No need to install swagger in stacker files, that part is now in the Makefile as a dependency for binaries.

build: remove swagger install in stacker files

---

Makefile

Adds a way to list imports used by specific binaries
This commit adds a new Make target that makes use of go list to show directly
imported packages in a given binary.
This target should be added in all future targets that build binaries, if listing
imported packages is important.
Existing targets were modified to include list-imports. Also, since list-imports
depends on EXTENSIONS variable, a dummy tag is used to overwrite the defaults of
this variable in case of minimal-type targets.
feature

Add a way to list imports used by specific binaries

---

.github/workflows/ci-cd.yml

When we publish a new release for zot there will be a new tag for our image, so we need to update the value of the "tag" field from our helm chart(from project-zot/helm-charts/charts/zot)
By this PR it will be automatically updated the values of "tag", "apiVersion" and "version" fields from project-zot/helm-charts/charts/zot.
```release-note
```
By submitting this pull request, I confirm …

Update automatically helm chart when publish a new release for zot

---

pkg/cli/extensions_test.go
pkg/test/common.go

config file may get removed before fsnotify starts watching it
make sure the config file gets removed when test ends, closes #608
```release-note
```

Fix test data races

---

pkg/storage/local.go
pkg/storage/local_test.go

fix GetReferrers function to be able to retrieve referrers of any specified artifactType
Even though the route handler filters for anything not of type  application/vnd.cncf.notary.v2.signature, the GetRefferrers function should not overwrite the artifactType and be prepared for other types.
overwriting artifactType instead of using the one provided as an argument to GetReferrers 
Even though the route handler filters for anything not of type  application/vnd.cncf.notary.v2.signature, the GetRefferrers function should not overwrite the artifactType and be prepared for other types.
**Testing done …

GetRefferers of any artifactType, not just application/vnd.cncf.notary.v2.signature

---

pkg/extensions/search/common/common_test.go
pkg/extensions/search/common/oci_layout.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.graphql
pkg/test/mocks/oci_mock.go

feature
#666
ImageListWithLatestTag currently returns a list of ImageInfo objects.
It needs to return consistent results with the API used for Global search as the same information will be used by the UI in the same type or cards.
So we need to update RepoSummary to include the data which right now is present in ImageInfo, but missing from RepoSummary (information on the latest tag in that specific repo).
Will update return type of ImageListWithLatestTag in a later PR (issue tracked in a separate GH issue)
Existing and updated automated tests.
No
Yes it …

RepoSummary has a new attribute NewestTag of type ImageSummary

---

Makefile
README_fuzz.md
pkg/storage/local.go
pkg/storage/local_test.go
pkg/storage/storage_test.go
test/scripts/fuzzAll.sh

feature
1. It is meant to introduce fuzzing, using native go fuzzing engine and ~~https://github.com/AdaLogics/go-fuzz-headers~~ to generate data for fuzz tests
**UPDATE**: go-fuzz-headers fails to generate data as go fuzz engine mutates input. go-fuzz-headers requires a specific amount  of bytes, which can't be guaranteed when data is mutated.
2. Fuzz tests require an initial seed corpus, which in Zot's case is cloned right before fuzzing starts from a separate repo https://github.com/project-zot/test-data
3. A Make target was created for running all Fuzz tests sequentially, each for a default period of 10s ( which can be overriden)
**This PR contains fuzz tests for all implementations of storage interface in storage_fs.** …

Fuzzing for local storage

---

.github/workflows/stale.yaml
.github/workflows/sync-golang-image.yaml

Looks like read|write is not a correct value:
https://github.com/project-zot/zot/actions/runs/2743961177
https://github.com/project-zot/zot/actions/runs/2743965531
Write should include both, so let's try to use that.

Fix permissions for image sync and stale workflows

---

pkg/api/routes.go
pkg/compliance/v1_0_0/check.go
swagger/docs.go
swagger/swagger.json
swagger/swagger.yaml

Signed-off-by: Bogdan BIVOLARU <bbivolar@cisco.com>
bug
In case we receive an invalid manifest (docker) we used to return 'Unsupported Media Type' HTTP error code 415, without any HTTP body. This adds a HTTP body which spells it out for the user.
Makes docker fail with a clear reason, since docker sees an invalid manifest error and retries with a valid OCI manifest format.
fixes: #534 
```bash
sudo docker push reg.mydomain2.com:8080/test:test
The push refers to repository [reg.mydomain2.com:8080/test]
65110baad718: Pushing [==================================================>]  1.947MB …
```

Make rejecting docker manifests more explicit

---

pkg/extensions/search/common/common_test.go
pkg/extensions/search/common/oci_layout.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go

feature
ExpandedRepoInfo currently returns RepoInfo that is a list of Manifests.
To comply with the newest UI requirements, a new field called Summary,
referring to RepoSummary structure, was added.
UI
This PR closes [#644](https://github.com/project-zot/zot/issues/664)

RepoInfo structure now includes new field representing RepoSummary

---

pkg/extensions/search/common/oci_layout.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/test/mocks/oci_mock.go

replace dependency of tagsInfo with list of manifests since only the manifest Digest is needed
```release-note
```

replace dependency of tagsInfo with list of manifests

---

pkg/api/controller.go
pkg/api/controller_test.go

fix for feature
Part of #606
Adds content-type to Access-Control-Allow-Headers to the CORS header function. Needed for the preflight of the GQL playground.
Playground won't work on downgrade

GQL Playground: Added content-type to Access-Control-Allow-Headers

---

pkg/api/routes.go
pkg/api/routes_test.go
pkg/extensions/sync/utils.go
pkg/storage/local.go
pkg/storage/local_test.go
pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go
pkg/storage/storage.go
pkg/storage/storage_test.go
pkg/test/mocks/image_store_mock.go

bug
This indirectly fixes hitting the FD limit when reading blobs from the disk when using the graphql API
Makes sure file handlers are timely closed after reading blobs.
Tested changeset in https://github.com/project-zot/zot/pull/457.
The environment had roughly 100 images (4 repos with multiple tags in each, 1042 individual blob files) in storage.
Before the fix, `bin/zli-linux-amd64 images local` used to cause FD limit to be reached when the file handlers for blobs remained open.
Repeated the test mentioned above with the patchset cherry-picked on top of …

Fix file handlers not being closed after calls to ImageStore.GetBlob

---

golangcilint.yaml
pkg/cli/client.go
pkg/cli/client_test.go
pkg/cli/cve_cmd.go
pkg/cli/cve_cmd_test.go
pkg/cli/image_cmd.go
pkg/cli/image_cmd_test.go
pkg/cli/searcher.go
pkg/cli/service.go
pkg/extensions/search/common/common.go
pkg/extensions/search/common/common_test.go
pkg/extensions/search/common/oci_layout.go
pkg/extensions/search/cve/cve.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/cve/models.go
pkg/extensions/search/digest/digest.go
pkg/extensions/search/digest/digest_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go

Signed-off-by: Roxana Nemulescu <roxana.nemulescu@gmail.com>
```release-note
```

[cloud usecase] zot cli should not download manifests when listing images

---

examples/config-tls.json
pkg/api/authz.go
pkg/api/controller_test.go
pkg/api/routes.go
pkg/extensions/extension_search.go
pkg/extensions/search/common/common_test.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.resolvers.go
pkg/requestcontext/context.go
pkg/test/common.go
pkg/test/common_test.go
pkg/test/dev.go
pkg/test/inject_test.go
pkg/test/prod.go

- AccessControlContext now resides in a separate package from where it can be imported,
along with the contextKey that will be used to set and retrieve this context value.
- AccessControlContext has a new field called Username, that will be of use for future
implementations in graphQL resolvers.
- GlobalSearch resolver now uses this context to filter repos available to the logged user.
Closes #615
feature
using authz context for use on GraphQl resolvers
**Does this PR introduce any user-facing …

graphql: Apply authorization on /_search endpoint

---

pkg/extensions/search/common/common_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/resolver.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go

ui
#663
From #663:
> ImageListWithLatestTag currently returns a list of ImageInfo objects. It needs to return consistent results with the API used for Global search as the same information will be used by the UI in the same type or cards.
Needed schema changes from #696 

GraphQL: RepoListWithNewestImage to return list of RepoSummary

---

.github/workflows/benchmark.yaml
.github/workflows/cluster.yaml
cmd/zb/helper.go
cmd/zb/perf.go

Signed-off-by: Roxana Nemulescu <roxana.nemulescu@gmail.com>
GetCatalog() uses empty storage for benchmarking.
Populate with mix of many small, medium and large images.

zb: populate images first for the GetCatalog test

---

pkg/api/config/config.go
pkg/api/config/config_elevated_test.go
pkg/api/config/config_test.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/cli/root.go
pkg/cli/root_test.go
pkg/extensions/sync/sync_test.go

currently different subpaths can only point to same root directory only
when one of storage config does not enable dedupe.
different subpath should be able to point to same root directory and in
that case their storage config should be same i.e GC,Dedupe, GC delay
and GC interval

storage: different subpaths can point to same root directory

---

pkg/extensions/search/common/common_test.go
pkg/extensions/search/common/oci_layout.go

feature
Closes https://github.com/project-zot/zot/issues/704
It skips manifests of a repo that don't have an annotation tag.
tests add a manifest that doesn't have a tag as a manifest.Annotations field and expect this manifest will be skipped
on calls such as ExpandedRepoInfo
```release-note
```

Skip manifest which have no annotation for tags

---

errors/errors.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/cli/root.go
pkg/cli/root_test.go

Based off of the PR by @thesayyn
https://github.com/project-zot/zot/pull/720
feature
issue #717 
Supports kernel-chosen random ports
No
```release-note
```

report listening port when chosen by kernel

---

.github/workflows/dco.yml

GitHub allows a "Squash and Merge" model which does an automatic rebase but commit GPG signature is from GitHub. So disable DCO checks only when merging.
ci/cd

dco: enable DCO checks only on PRs

---

pkg/api/controller.go
pkg/api/controller_test.go
pkg/cli/client.go
pkg/extensions/lint/lint_test.go
pkg/extensions/scrub/scrub_test.go
pkg/extensions/search/common/common_test.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/cve/trivy/scanner_internal_test.go
pkg/extensions/search/digest/digest_test.go
pkg/extensions/search/resolver_test.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/utils.go
pkg/storage/common.go
pkg/storage/common_test.go
pkg/storage/local/local.go
pkg/storage/local/local_elevated_test.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3.go
pkg/storage/scrub_test.go
pkg/storage/storage_controller.go
pkg/storage/storage_test.go

Cleanup storage code, moved some common code into helper.go

storage: Move common code in helper functions, closes #730

---

.github/workflows/golangci-lint.yaml
Makefile
pkg/api/routes.go
pkg/debug/swagger/swagger.go
pkg/debug/swagger/swagger_disabled.go

Also added the "debug" build tag in the binary-debug Make target
cleanup
swagger is not needed for the minimal and regular binary builds
Also moved binary-minimal to be the first in the Makefile

build(swagger): removed swagger requirement from binary-minimal and binary

---

Makefile

Earlier checks did not report non-golang code dependencies. Now they do, so account for that.
bug
License checker in ci/cd is stuck otherwise.

fix(license-check): also account for another result condition

---

examples/config-search.json
pkg/api/routes.go
pkg/debug/constants/consts.go
pkg/debug/gqlplayground/gqlplayground.go
pkg/debug/gqlplayground/gqlplayground_disabled.go
pkg/debug/gqlplayground/index.html.tmpl
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/schema.graphql

feature
#606 
This PR adds a new make target that builds zot to also serve a GraphQL playground (GraphiQL)
Users will be able to access the new endpoint
```release-note
```

feat(GraphQL): playground, served by zot in specific binary

---

pkg/debug/gqlplayground/gqlplayground.go

quickfix
Fixes ncorrect path for playground template
Accessing the playground endpoint results in a blank page

fix: incorrect path for playground template

---

.github/workflows/branch-cov.yml
.github/workflows/codeql-analysis.yml
.github/workflows/golangci-lint.yaml
CONTRIBUTING.md
Makefile
pkg/api/controller_test.go
pkg/api/routes_test.go
pkg/cli/cli.go
pkg/cli/client.go
pkg/cli/client_elevated_test.go
pkg/cli/client_test.go
pkg/cli/config_cmd.go
pkg/cli/config_cmd_test.go
pkg/cli/cve_cmd.go
pkg/cli/cve_cmd_test.go
pkg/cli/extensions_test.go
pkg/cli/image_cmd.go
pkg/cli/image_cmd_test.go
pkg/cli/minimal.go
pkg/cli/repo_cmd.go
pkg/cli/searcher.go
pkg/cli/service.go
pkg/extensions/README.md
pkg/extensions/extension_search.go
pkg/extensions/extension_search_disabled.go
pkg/log/log_test.go
pkg/test/common_test.go
test/scripts/fuzzAll.sh

It was not used for UI, it had become a CLI dependency with the same functionality as search
build
cleanup
ci
We had a redundant build tag `ui_base` which was basically the same as `search`.
It was used for cli, not ui.
Cleanup in preparation of adding a `ui` tag
The `ui_base` build tag/label will have no effect.

build(tags): remove redundant build tag ui_base

---

pkg/extensions/search/common/common.go
pkg/extensions/search/common/oci_layout.go
pkg/extensions/search/resolver.go
pkg/test/mocks/oci_mock.go

The lastUpdated field was picked from the first entry in image history Now it is the created time of the image, or the last entry in image history, if created time is unavailable
bug
lastUpdated was computed based on wrong fields

fix(lastUpdated): fix image lastUpdated timestamp logic

---

.github/workflows/ci-cd.yml
Makefile
pkg/api/config/config.go
pkg/extensions/extension_search.go
stacker.yaml

documentation I think
#852
This PR gets the commit hash and writes it into the new CommitHash variable in api.Config, which is used in the discovery api to point to the extensions readme link of the used build:
```
curl localhost:5000/v2/_oci/ext/discover
{"extensions":[{"name":"_zot","url":"https://github.com/project-zot/zot/blob/v1.4.3-rc2/pkg/extensions/_zot.md","description":"zot registry extension","endpoints":["/v2/_zot/ext/search"]}]}
```

build: add commit hash to Config at build for proper discovery readme

---

.github/workflows/ecosystem-tools.yaml
Makefile
test/blackbox/annotations.bats

Solves #850 
```release-note
```

test: Build images with annotations

---

.github/workflows/ci-cd.yml
examples/cluster/haproxy.cfg
pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go

Remove sticky sessions from clustering
cleanup
Removes the need of sticky sessions in zot cluster load balancer (haproxy)
no

fix(s3): remove tracking multipart uploads

---

examples/config-lint.json
pkg/api/controller_test.go
pkg/cli/client_test.go
pkg/cli/cve_cmd_test.go
pkg/cli/extensions_test.go
pkg/cli/image_cmd_test.go
pkg/extensions/config/config.go
pkg/extensions/extensions_test.go
pkg/extensions/lint/lint.go
pkg/extensions/lint/lint_test.go
pkg/extensions/monitoring/monitoring_test.go
pkg/extensions/scrub/scrub_test.go
pkg/extensions/search/common/common_test.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/digest/digest_test.go
pkg/extensions/sync/sync_test.go
test/blackbox/annotations.bats

cleanup
Some extensions (like lint) are not consistent in the config params, so fixing.

fix(config): make all extension config consistent

---

pkg/api/controller_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

bug
#891
Coverage sometimes failed for a function within the scheduler code. There was a range of a slice that was iterated upon and then modified, leading to unexpected behavior. 
Also adds a test to check for the waiting task generator (tested with 150 runs) + fixes a periodic GC test that sometimes failed because it didn't have enough time to execute its async task (ran it 500 times on my machine to ensure it passes consistently)

fix: flaky scheduler coverage

---

pkg/cli/cve_cmd_test.go
pkg/cli/image_cmd_test.go
pkg/extensions/search/cve/cve_test.go
pkg/test/common.go
pkg/test/common_test.go

fix: replace time.sleep() with checking logs

---

pkg/extensions/sync/on_demand.go
pkg/extensions/sync/signatures.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/utils.go

fix(sync): fixed broken logic to get tags for repo

---

pkg/cli/cve_cmd.go
pkg/cli/discover.go
pkg/cli/image_cmd.go
pkg/cli/service.go

Issues fixed:
- the cli calls reaching out to the catalog endpoint used to request signature manifests
- resty was used instead of the cli http client to check if the discovery api was available but it did not take into account TLS verification configuration (testing locally with self-signed certificates did not work)
(cherry picked from commit ca42031ae9b1ceb459f5cd4f86cb82b3c9f78157)
bug/refactoring
Tested

fix(cli): do not show signatures and fix tls verification client side

---

pkg/api/controller_test.go
pkg/cli/cve_cmd_test.go
pkg/cli/image_cmd_test.go
pkg/extensions/search/common/common_test.go
pkg/extensions/search/digest/digest_test.go

cleanup
Sometimes unpredictable issues when running digest tests individually due to global vars, this PR removes the global vars and updates the test setup helper function
Also removes a bunch of hardcoded digests I missed in my last PR

refactor(tests): removed globals from digest test, more hardcoded digests

---

Makefile
errors/errors.go
examples/README.md
examples/config-policy.json
pkg/api/authz.go
pkg/api/controller_test.go
pkg/api/routes.go
pkg/api/routes_test.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/sync/sync_test.go
pkg/requestcontext/context.go
pkg/storage/common.go
pkg/storage/local/local.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go
pkg/storage/storage.go
pkg/storage/storage_test.go
pkg/test/mocks/image_store_mock.go
test/blackbox/anonymous_policy.bats
test/blackbox/detect_manifest_collision.bats

Suppose we push two identical manifests (sharing same digest) but with different tags, then deleting by digest should throw an error otherwise we end up deleting all image tags (with gc) or dangling references (without gc)
This behaviour is controlled via Authorization, added a new policy action named detectManifestsCollision which enables this behaviour
**Does this PR introduce any …

fix(storage): deleting manifests with identical digests

---

pkg/api/controller_test.go
pkg/api/routes.go

oras cli now allows for different artifactTypes. Originally, zot was interested in the notation use case only. No reason to constrain.
```release-note
```

fix(oras): relax artifactType check to allow other types

---

pkg/extensions/search/common/common_test.go
pkg/extensions/search/common/model.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go
pkg/test/common.go
pkg/test/common_test.go

UI can now make use of OCI artifacts and references using `Referrers` gQL query. It returns a list of descriptors that refer on their `subject` field to another digest.
Closes https://github.com/project-zot/zot/issues/1006
Signed-off-by: Alex Stan <alexandrustan96@yahoo.ro>
feature
UI can now use gQL queries to get list of referrer artifacts
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

feat(graphql): add an api to return referrers

---

pkg/api/routes.go

notation sign image index exits with "missing Content-Length" error
```release-note
```

fix(routes): set Content-Length on GetManifest

---

pkg/api/controller_test.go
pkg/storage/local/local_test.go

fix(test): consolidate flaky scrub test

---

pkg/extensions/search/common/common_test.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/schema.resolvers.go

Currently there is no push-back on queries that should contain image names but have only the repo name. This commit adds a check that will return an error for images w/o a reference(tag or digest).
feature
closes https://github.com/project-zot/zot/issues/908
```release-note
```

fix: queries with images without a reference should return an error

---

pkg/storage/scrub.go
pkg/storage/scrub_test.go

feat(scrub): add scrub logic for ImageIndex media type

---

swagger/docs.go

- Update docs.go - fix typo
- swagger.json has typo.
- [swagger.json](https://github.com/project-zot/zot/blob/main/swagger/swagger.json) open by swagger-ui
- None.
- None.
- No.
- No.

fix(swagger): update docs.go - fix typo

---

Makefile
pkg/extensions/sync/utils.go
test/blackbox/sync_docker.bats

fix(sync): fix sync on demand with docker library

---

.github/workflows/scorecards.yml
.github/workflows/stale.yaml
go.mod
go.sum

https://github.com/project-zot/zot/pull/1087
https://github.com/project-zot/zot/pull/1088
https://github.com/project-zot/zot/pull/1089
```release-note
```

chore(deps): fix dependabot alerts

---

.github/workflows/ci-cd.yml
pkg/storage/s3/s3_test.go

fix(test): use correct aws region for dynamodb

---

.github/workflows/sync-3rdparty-images.yaml

This will replace calls made directly to ghcr.io/aquasecurity/trivy-db Which are hitting the rate limiter

ci(trivy): copy trivydb oci artefact to project-zot repo

---

test/blackbox/annotations.bats

cleanup
ci
Building the zot container image just to use as a test image to copy over takes too long, uses too many resources, and is not necessary.
Build a simpler image for the purpose of testing annotations instead.

fix(ci): do not build zot container image for the annotation tests

---

go.mod
pkg/extensions/search/cve/trivy/cache.go
pkg/extensions/search/cve/trivy/scanner.go

feature
Right now the trivy scanner logic is triggered every time a call is made to scan an image.
By caching the results, we can avoid some of the repetitive calls made for the same image (specifically in the UI use case).
We can also add pagination on the results if we already have them cached (which is a separate commit which will be ported to main branch after this one is merged).

feat(cve): cache trivy results for an image:tag

---

pkg/cli/image_cmd_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_test.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go
pkg/meta/repodb/pagination.go
pkg/meta/repodb/repodb.go
pkg/meta/repodb/repodb_test.go
pkg/test/mocks/repo_db_mock.go

ImageListForDigest can now return paginated results, directly from DB. It uses FilterTags, a new method to filter tags (obviously) based on the criteria provided in the filter function.
Pagination of tags is now slightly different, it shows all results if no limit and offset are provided.
Signed-off-by: Alex Stan <alexandrustan96@yahoo.ro>
bug(tests): cli tests for digests expecting wrong size
(cherry picked from commit 369216df931a4053c18278a8d89f86d2e1e6a436)
feature
The call ImageListForDigest  was not returning paginated results, actually it was not returning data from RepoDB, it was using the layout.
**What does this PR do / …

feat(repodb): add pagination for ImageListForDigest and implement FilterTags

---

pkg/extensions/search/common/common_test.go
pkg/extensions/search/convert/convert_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper_test.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_test.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go
pkg/meta/repodb/pagination.go
pkg/meta/repodb/pagination_test.go
pkg/meta/repodb/repodb.go
pkg/meta/repodb/repodb_test.go
pkg/test/mocks/repo_db_mock.go

feat(repodb): add PageInfo to GlobalSearch and RepoListWithNewestImage results

---

pkg/extensions/search/common/common_test.go
pkg/extensions/search/resolver.go

(cherry picked from commit e99ea64bd1b9699bcd6d72183c722d636772bbb1)
Resolves #958

fix: Sort tags returned by ExpendedRepoInfo in the Images property with the newest first

---

pkg/storage/constants/constants.go

"If filtering is requested and applied, the response MUST include an annotation (org.opencontainers.referrers.filtersApplied) denoting that an artifactType filter was applied.""
```release-note
```

fix(referrers): annotation key is incorrect

---

pkg/cli/image_cmd_test.go
pkg/cli/searcher.go
pkg/cli/service.go
pkg/extensions/search/common/common_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_test.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go
pkg/meta/repodb/repodb.go
pkg/meta/repodb/repodb_test.go
pkg/test/mocks/repo_db_mock.go

- derivedImageList and baseImageList now use FilterTags to obtain results, each with its own filter function
- images that have the exact same manifest as the one provided as a parameter are no longer considered base images or derived images
- both calls can be made with specific pagination parameters, and the response will include PageInfo
Signed-off-by: Alex Stan <alexandrustan96@yahoo.ro>
fix(tests): fix one of the pagination tests
The results were not reliable as the 2 returned tags were sorted by created date/time which was not set, resulting in an unpredictable order
(cherry picked from commit be504200a1127371422aeb0e5c0219e2a1ead20a) (cherry picked from commit ed8d797e639f262a63840120afe92da7db9a7600)
Signed-off-by: Andrei Aaron …

feat(repodb): DerivedImageList and BaseImageList make use of RepoDB

---

go.mod
pkg/extensions/search/cve/trivy/cache.go

We are now using v2.0.1 in the cve cache logic.
Unfortunately we are also using v0.5.4 indirectly, as it is required for gqlgen, see: https://github.com/99designs/gqlgen/blob/e6114a2c6af22bcdc92180660a58e6125e7946ad/go.mod#L7

chore: update the version of go-lru we use to the latest available

---

.github/workflows/ci-cd.yml

The cache should not be the same if we build for different OSs/architectures
See #1167

ci(cache): split go build cache from go modules cache

---

pkg/extensions/search/cve/pagination_test.go
pkg/extensions/search/cve/trivy/scanner_internal_test.go

The 'test' makefile target runs the tests for both 'minimal' and equivalent of the former 'extended' build. The trivy package tests were run twice, even if the trivy logic is unreachable if search is disabled. With this update we should see a cut of about 150s of test time.

test: avoid running trivy tests if search build label is missing

---

Makefile

Exit code was not correctly handled because of the pipes/tee, so the job would not fail if tests were failing. Reverting this for now.
This reverts commit 74013a71afa925a1c897f4e371fd4a2deacc8cc7.

ci: Revert "test: show the execution times of the tests (#1163)"

---

pkg/api/controller.go
pkg/api/controller_test.go
pkg/api/routes.go
pkg/cli/cve_cmd_test.go
pkg/cli/image_cmd_test.go
pkg/cli/root.go
pkg/cli/root_test.go
pkg/compliance/v1_0_0/check_test.go
pkg/exporter/api/controller_test.go
pkg/extensions/extension_search.go
pkg/extensions/extension_search_disabled.go
pkg/extensions/search/common/common_test.go
pkg/extensions/sync/sync_test.go
pkg/test/common.go
pkg/test/common_test.go

- refactor(cve): remove the global of type cveinfo.CveInfo from the extensions package Replace it with an attribute on controller level
- refactor(controller): extract initialization logic from controller.Run()
- test(cve): mock cve scanner in cli tests

refactor(cve): improve CVE test time by mocking trivy

---

.github/workflows/ci-cd.yml

This should not be necessary for public repos,
but should help with rate limiting

chore(codecov): use a token to authenticate to codecov

---

pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/schema.graphql

This is for consistency with the other calls, and should help in making all ZUI handling of ZOT errors consistent

feat(graphql): Image() call now returns a non-nullable ImageSummary

---

go.mod
go.sum

chore(go.mod): fix dependabot alerts

---

pkg/extensions/sync/on_demand.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_test.go
pkg/extensions/sync/utils.go

feat(sync): skip already synced images in sync ondemand

---

examples/config-anonymous-authz.json
examples/config-ldap.json
examples/config-policy.json
pkg/api/authn.go
pkg/api/authz.go
pkg/api/config/config.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/api/ldap.go
pkg/api/routes.go
pkg/cli/config_reloader_test.go
pkg/cli/root.go
pkg/cli/root_test.go
pkg/requestcontext/context.go
pkg/test/common_test.go
test/blackbox/anonymous_policy.bats
test/blackbox/detect_manifest_collision.bats

feat(authz): added groups mechanism

---

pkg/extensions/extension_search.go

The condition to generate trivyDB download tasks was bugged, and new tasks were generated in case the download had already been successful (state `done`).

bug(cve): fix trivyDB being downloaded multiple times in a loop

---

pkg/extensions/search/cve/pagination.go
pkg/extensions/search/cve/trivy/scanner.go
pkg/extensions/search/resolver.go
pkg/extensions/sync/sync_test.go
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go
pkg/meta/repodb/pagination.go
pkg/meta/repodb/update/update.go

cleanup
#1188
Removes usage of deprecated package pkg/errors
```release-note
```

chore(deps): remove usage of deprecated package pkg/errors

---

pkg/api/errors.go
pkg/api/routes.go
pkg/extensions/lint/lint.go
pkg/extensions/lint/lint_test.go

putting this info into error detail would be ideal, but skopeo doesn't print them, so overwrite the error message.
#1145
```release-note
```

feat(routes): better error message in case of missing annotations

---

pkg/extensions/search/common/common_test.go
pkg/extensions/search/common/model.go
pkg/extensions/search/convert/convert_test.go
pkg/extensions/search/convert/repodb.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.graphql
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper_test.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_test.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go
pkg/meta/repodb/load_repodb.go
pkg/meta/repodb/load_repodb_test.go
pkg/meta/repodb/repodb.go
pkg/meta/repodb/repodb_test.go
pkg/meta/repodb/update/update_test.go
pkg/test/mocks/repo_db_mock.go
test/blackbox/referrers.bats

Changed repodb to store more information about the referrer needed for the referrers query
#1238
```release-note
```

feat(search): add referrers field to ImageSummary

---

pkg/storage/cache/dynamodb.go
pkg/storage/local/local.go

feat: cleanup error msgs

---

Makefile

This is to avoid situations such as https://github.com/project-zot/zot/pull/1150 where an indirect dependency became direct without a corresponding go.mod change

ci(go.mod): verify go.mod and go.sum don't have uncommitted changes after `go mod tidy`

---

pkg/api/controller_test.go
pkg/extensions/search/common/common_test.go
pkg/extensions/search/common/model.go
pkg/extensions/search/common/oci_layout.go
pkg/extensions/search/convert/repodb.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/search.md
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go
pkg/meta/repodb/common.go
pkg/meta/repodb/common/common.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go
pkg/meta/repodb/repodb_test.go

feat(search): update search pattern matching rules

---

pkg/api/controller.go
pkg/api/routes.go
pkg/extensions/extension_sync.go
pkg/extensions/extension_sync_disabled.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/test/common.go

sync: remove sync WaitGroup, it's stopped with context
```release-note
```

test: stop task scheduler between test runs

---

pkg/cli/root.go

bug: replaced printing the port with logging it when chosen dynamically

---

pkg/extensions/sync/sync_test.go

test(sync): make sure sync doesn't write on shutdown

---

examples/kind/kind-with-registry.sh

Add examples/kind-with-registry.sh to start a kind cluster with zot as a local registry.
```release-note
```

feat: add a kind cluster example

---

pkg/api/authz.go
pkg/requestcontext/context.go

fix(authz): get username from authn.go request context

---

pkg/api/controller.go
pkg/api/routes.go
pkg/cli/config_reloader.go
pkg/cli/root.go
pkg/common/common.go
pkg/exporter/api/exporter.go
pkg/extensions/extension_sync.go
pkg/extensions/monitoring/minimal.go
pkg/extensions/search/convert/repodb.go
pkg/extensions/search/cve/cve.go
pkg/extensions/search/cve/trivy/scanner.go
pkg/extensions/search/resolver.go
pkg/extensions/search/schema.resolvers.go
pkg/extensions/sync/on_demand.go
pkg/extensions/sync/signatures.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_test.go
pkg/extensions/sync/utils.go
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go
pkg/meta/repodb/repodbfactory/repodb_factory.go
pkg/meta/repodb/storage_parsing.go
pkg/meta/update.go
pkg/storage/cache/boltdb.go
pkg/storage/cache/dynamodb.go
pkg/storage/common.go
pkg/storage/local/local.go
pkg/storage/s3/s3.go
pkg/test/oci-layout/oci_layout.go

Closes #1366 
```release-note
```

feat: remove usage of zerolog.Logger.Msgf() from zot code

---

pkg/storage/common.go
pkg/storage/common_test.go

Currently, when pushing an image, validation is performed to check that a layer/blob in the manifest already exists. For non-distributable layers, that check needs to be skipped.
Fixes issue #1394
```release-note
```

fix: non-distributable layers may not exist

---

pkg/extensions/sync/sync_test.go
pkg/extensions/sync/utils.go

fix(sync): skip non distributable layers

---

pkg/api/constants/consts.go
pkg/api/routes.go
pkg/api/routes_test.go
pkg/extensions/search/cve/trivy/scanner_internal_test.go
pkg/extensions/search/search_test.go
pkg/extensions/sync/signatures.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/utils.go
pkg/meta/update.go
pkg/storage/common_test.go
pkg/storage/local/local.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go
pkg/storage/scrub_test.go
pkg/storage/storage.go
pkg/storage/storage_test.go
pkg/test/common.go
pkg/test/common_test.go
pkg/test/mocks/image_store_mock.go

Closes #1410
```release-note
```

Update referrers response

---

cmd/zb/helper.go
cmd/zb/main.go
cmd/zb/perf.go
pkg/storage/local/local.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go

fix(storage): also put deduped blobs in cache, not just origin blobs
this caused an error when trying to delete deduped blobs from multiple repositories
```release-note
```

fix(zb): fixed remote repositories cleanup

---

errors/errors.go
go.mod
pkg/extensions/search/convert/convert_test.go
pkg/extensions/search/convert/repodb.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/schema.graphql
pkg/extensions/sync/signatures.go
pkg/extensions/sync/sync_test.go
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go
pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper_test.go
pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go
pkg/meta/repodb/repodb.go
pkg/meta/repodb/repodbfactory/repodb_factory.go
pkg/meta/repodb/repodbfactory/repodb_factory_test.go
pkg/meta/repodb/storage_parsing.go
pkg/meta/repodb/storage_parsing_test.go
pkg/meta/signatures/cosign.go
pkg/meta/signatures/notation.go
pkg/meta/signatures/signatures.go
pkg/meta/signatures/signatures_test.go
pkg/meta/update.go
pkg/meta/update_test.go
pkg/test/mocks/repo_db_mock.go

feat(graphql & repodb): add info about signature validity

---

pkg/storage/local/local_test.go
pkg/storage/s3/s3_test.go

fix(test): fix storage flaky tests

---

pkg/storage/common/common.go
pkg/storage/constants/constants.go

As per latest dist-spec, this is now removed.
```release-note
```

fix: revert "org.opencontainers.referrers.filtersApplied"

---

go.mod
go.sum

chore(deps): downgrade golang-lru

---

.github/workflows/ci-cd.yml
Makefile
pkg/api/routes_test.go
pkg/extensions/extension_search_test.go

ci(workflow): show disk usage and free up disk space used by unneeded tooling
ci(tests): routes tests: do not copy large images if they are not used later
ci(trivy): update a test: download trivy.db to a temporary folder

ci(disk usage): disk related fixes and improvements

---

pkg/api/routes.go
pkg/common/common.go
pkg/extensions/sync/references/cosign.go
pkg/extensions/sync/references/oci.go
pkg/extensions/sync/references/oras.go
pkg/extensions/sync/references/references.go
pkg/extensions/sync/references/references_internal_test.go
pkg/extensions/sync/service.go
pkg/extensions/sync/sync_test.go
pkg/storage/local/local.go
pkg/storage/s3/s3.go

feature
[#1334](https://github.com/project-zot/zot/issues/1334)
sync now also pulls chained artifacts recursively
eg:
image->sbom->sbom signature
image->artifact->artifact
added chained artifacts in sync_test.go/TestSignatures()
no
```release-note
```

feat(sync): sync references(signatures/artifacts) recursively

---

pkg/extensions/extension_mgmt.go
pkg/extensions/extension_userprefs.go
swagger/docs.go
swagger/swagger.json
swagger/swagger.yaml

added swagger doc generation for mgmt and userprefs

---

pkg/extensions/sync/remote.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/extensions/sync/utils.go
test/blackbox/sync_docker.bats

bug
https://github.com/project-zot/zot/issues/1490
currently docker images are downloaded every time, because comparison between remote and local is done before conversion of docker images to oci.
convert docker manifests to oci manifests before syncing, compare with local one and skip if it's already synced
no
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

fix(sync): fixed skipping docker images when they already synced

---

pkg/extensions/sync/sync_internal_test.go

fix(sync): flaky test on fetching tags

---

build/stacker.yaml

build: ui extension needs mgmt

---

pkg/api/routes.go

because UI routes will setup a http.FileServer on '/' any router setup after UI will be ignored at runtime becuase gorrilla will route it to http.Fileserver instead.
bug
https://github.com/project-zot/zot/issues/1565
```release-note
```

fix(extensions): setup UI extension as last one

---

errors/errors.go
pkg/cli/cve_cmd.go
pkg/cli/cve_cmd_test.go
pkg/cli/service.go
pkg/extensions/search/cve/trivy/scanner.go
pkg/extensions/search/cve/trivy/scanner_internal_test.go

Without the changes to check if the CVE DB is already downloaded, relying on the trivy library itself for error handling had some issues, as sometimes the files it opens (the cache DB, different from the CVE DB - called fanal.db) were not closed.
This was causing issues on subsequent calls, even if the CVE DB was downloaded in the meantime.
zli will now make repeated attempts to search in case of this error. This will take care of the flaky CVE test in the ecosystem tools.

fix(CVE): attempt to scan now returns early with an error if trivyDB metadata json is missing

---

pkg/api/authz.go
pkg/api/routes.go
pkg/extensions/README.md

feature
- AuthzHandler has now been split in BaseAuthzHandler and DistSpecAuthzHandler
The former populates context with user specific data needed in most handlers, while
the latter executes access logic specific to distribution-spec handlers.
```release-note
```

refactor: split AuthZ mdw in 2 different parts, each for a specific purpose

---

pkg/api/controller_test.go
pkg/storage/common/common.go
pkg/storage/local/local.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go
pkg/storage/storage_test.go
pkg/storage/types/types.go
pkg/test/mocks/image_store_mock.go

when pushing manifests, zot will validate blobs (layers + config blob) are present in repo, currently it opens(in case of filesystem storage) or download( in case of cloud storage) each blob.
fixed that by adding a new method ImageStore.CheckBlobPresence() on storage to check blobs presence without checking the cache like ImageStore.CheckBlob() method does.
bug
```release-note
```
By submitting this pull request, I confirm that my …

fix(storage): do not open/download blobs when validating manifests

---

.github/workflows/ci-cd.yml

this should clean localstack persisted data in tests
bug
clean test data persisted in localstack in s3/dynamodb tests
```release-note
```

fix(ci/cd): stop localstack after ci/cd pipeline

---

Makefile
errors/errors.go
pkg/extensions/extension_sync.go
pkg/extensions/sync/service.go
pkg/extensions/sync/sync_test.go
test/blackbox/sync_replica_cluster.bats

sync now ignores self referencing urls, this will help in clustering mode where we can have the same config for multiple zots
closes #1335
```release-note
```

feat(sync): sync can include self url in registry.URLs

---

pkg/common/http_server.go
pkg/extensions/extension_mgmt.go
pkg/extensions/extension_userprefs.go

move queryHasParams in common package
fixes building mgmt and userprefs separately
bug
currently mgmt can not be built without userprefs extension
fix that by moving queryHasParams into common package
```release-note
```

build: fix mgmt and userprefs when building them separately

---

pkg/cli/cve_cmd_test.go
pkg/cli/image_cmd_test.go
pkg/cli/service.go

Resolves #1597
Fix missing properties in some calls: OS/Arch/IsSigned/LastUpdated. Since the properties were missing from the graphql requests, zli was showing default values.
Update the tests to generate a tets image with the created date different from the go detault value for time.Time{}. The tests are now checking a non-default value in the responses client side, in order to avoid missing issues like this in the future.

fix(cli): make sure all needed ImageSummary properties are requested from the server

---

pkg/extensions/search/cve/trivy/scanner_test.go
pkg/test/common.go

fix(ci): trivy test to expect 3 CVEs instead of 2 in the vulnerable test layer

---

.github/workflows/oci-conformance-action.yml
pkg/api/controller_test.go
pkg/api/routes.go

https://github.com/opencontainers/distribution-spec/issues/448
Should only indicate what filter-type was applied and not what exact values it was filtered on.
```release-note
```

fix(conformance): OCI-Filters-Applied should return a literal

---

pkg/api/authn.go
pkg/api/controller_test.go

The ui sends the header X-ZOT-API-CLIENT=zot-ui regardless of session authentication status. In case of new sessions zot would reject the unauthenticated call on /v2 (which is used to determine if anonymous access is allowed by the server when the header was set) expecting all users sending this header to be already authenticated.
Since the ui received 401 from the server, it would not show the option for anonymous login.

fix(auth): fix anonymous auth for ui

---

pkg/api/controller.go
test/scripts/fuzzAll.sh
test/scripts/gen_certs.sh
test/scripts/gen_nameless_certs.sh

- Avoid hard-coding the path for bash - this typically is installed as /usr/local/bin/bash
- Allow for the fact that FreeBSD's rlimit uses signed integers
Almost all of the test suite passes with three test failures that I haven't tried to debug yet.
cleanup
Running zot test suite on FreeBSD, ad-hoc testing using zot as a local registry.
None
No
No
```release-note
None
```
By submitting this pull request, I confirm that my contribution is …

fix: freebsd build support

---

.github/workflows/ci-cd.yml
Makefile

ci: add freebsd target for releases

---

.github/workflows/oci-conformance-action.yml

Reverts part of de24bd937f20a66628fdacf4d658eb95df0b3769
```release-note
```

ci(conformance): revert to upstream OCI checks

---

.github/workflows/ci-cd.yml
Makefile
pkg/api/routes.go
swagger/docs.go
swagger/swagger.json
swagger/swagger.yaml

bug
On Mac OS the swagger target does nothing (because of using . or DOT in makefile target name)
```
aiandus-MacBook-Pro:zot aiandu$ make swagger
make: Nothing to be done for `swagger'.
```
```
make swagger
```
No

fix: swagger Makefile target broken on darwin

---

Makefile

feature
When user tries "make binary" or "make binary-minimal" on darwin for example, the Makefile correctly detects OS and ARCH and creates a proper binary instead of default one for linux/amd64
Manual testing on Linux amd64, Mac OS Ventura with Intel chipset,  FreeBSD v13.2 amd64.
To be tested on Mac OS with M1 chipset.
No
```release-note
```

feat: automated detection of OS and ARCH if unset

---

pkg/common/common.go
pkg/extensions/extension_image_trust.go
pkg/extensions/imagetrust/cosign.go
pkg/extensions/imagetrust/image_trust.go
pkg/extensions/imagetrust/image_trust_disabled.go
pkg/extensions/imagetrust/image_trust_disabled_test.go
pkg/extensions/imagetrust/image_trust_test.go
pkg/extensions/imagetrust/notation.go
pkg/extensions/sync/sync_test.go
pkg/meta/boltdb/boltdb.go
pkg/meta/boltdb/boltdb_test.go
pkg/meta/dynamodb/dynamodb.go
pkg/meta/meta.go
pkg/meta/meta_test.go
pkg/meta/parse.go
pkg/meta/parse_test.go
pkg/storage/common/common.go
pkg/storage/local/local.go

- the size of the binary-minimal becomes 32MB
- "signatures" package is renamed into "imagetrust" and moved under extensions
- if the binary is not built using "imagetrust" tag then the signatures verification will not be performed
```release-note
```

refactor: move /pkg/meta/signatures under /pkg/extensions/imagetrust

---

.github/workflows/oci-conformance-action.yml
errors/errors.go
pkg/api/authn.go
pkg/api/errors/errors.go
pkg/api/errors/errors_test.go
pkg/api/routes.go
pkg/extensions/extensions_lint_disabled.go
pkg/extensions/lint/lint.go
pkg/storage/common/common.go
pkg/storage/common/common_test.go

feature
https://github.com/project-zot/zot/issues/1418
Adds jsonSchema validation errors from image-spec to errors.details returned to the client: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#error-codes
Added UTs
No
No

feat: propagate detailed error msgs to client (OCI dist-spec format)

---

examples/README.md
examples/config-openid.json
pkg/api/authn_test.go
pkg/api/config/config.go
pkg/api/controller_test.go
pkg/api/routes_test.go
pkg/cli/root_test.go
pkg/extensions/extension_mgmt.go
pkg/extensions/extensions_test.go
swagger/docs.go
swagger/swagger.json
swagger/swagger.yaml
test/blackbox/cloud-only.bats
test/dex/config-dev.yaml

feature
none
This PR allow admin to add generic OIDC provider and customize it's name (linked with zui: https://github.com/project-zot/zui/pull/375)
Won't break on upgrade / downgrades
It allows the display of a customizable login button with the proper patch on zui (PR https://github.com/project-zot/zui/pull/375)

feat(authn): add generic oidc and allow customizable name

---

pkg/api/config/config.go
pkg/api/controller_test.go
pkg/cli/extensions_test.go

It is now enabled based only on search configuration

feat(mgmt): mgmt extention no longer depends on UI being enabled

---

pkg/extensions/monitoring/common.go
pkg/extensions/monitoring/extension.go
pkg/extensions/monitoring/minimal.go

bug
[DATA RACE in TestNewExporter](https://pipelines.actions.githubusercontent.com/serviceHosts/40249189-1287-49ef-b1f7-d89623a7edfc/_apis/pipelines/1/runs/96903/signedlogcontent/3?urlExpires=2023-09-06T09%3A32%3A21.2171590Z&urlSigningMethod=HMACV1&urlSignature=x%2Bn1ChpphggaDdVOdBaMjqdjB8MRVHBBCFkvp1%2BpqO0%3D)
enabling/disabling logic of metrics server for zot minimal (with zot exporter) moved to metrics server processing logic (inside Run() that uses channelized 1-request at a time logic- so no DATA RACE is expected...)
**Will this …

fix: DATA RACE in TestNewExporter

---

.github/dependabot.yml

Given the default limit is 5 and some packages like AWS release daily, having a weekly schedule results in the same packages being flagged for update most of the time.
Let's increase to 10 to make sure there are no issues in other libraries

chore(dependabot): increase the limit of dependabot PRs

---

examples/config-popular-registries.json
examples/config-sync.json
pkg/common/http_client.go
pkg/extensions/sync/httpclient/client.go
pkg/extensions/sync/references/cosign.go
pkg/extensions/sync/references/oci.go
pkg/extensions/sync/references/oras.go
pkg/extensions/sync/references/references.go
pkg/extensions/sync/service.go
test/blackbox/sync_docker.bats

closes: #1703
bug
Sync spams with json parsing errors in log messages, everytime it tries to ping docker, because it read the response body.
improve ping func()
```release-note
```

fix(sync): ping func should not try to read response body

---

pkg/api/controller.go
pkg/extensions/sync/sync_test.go
pkg/storage/imagestore/imagestore.go

reloading config from one without extensions
to one with extensions caused a panic
```release-note
```

fix(config): fix config reloader panic

---

pkg/cli/client/cve_cmd_internal_test.go
pkg/extensions/extension_search_test.go
pkg/extensions/search/convert/annotations.go
pkg/extensions/search/convert/convert_internal_test.go
pkg/extensions/search/convert/convert_test.go
pkg/extensions/search/convert/cve.go
pkg/extensions/search/convert/metadb.go
pkg/extensions/search/cve/cve.go
pkg/extensions/search/cve/cve_internal_test.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/cve/model/models.go
pkg/extensions/search/cve/pagination.go
pkg/extensions/search/cve/pagination_test.go
pkg/extensions/search/cve/trivy/scanner.go
pkg/extensions/search/cve/trivy/scanner_test.go
pkg/extensions/search/pagination/pagination_test.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.resolvers.go
pkg/extensions/search/search_test.go
pkg/meta/boltdb/boltdb.go
pkg/meta/parse.go
pkg/test/mocks/cve_mock.go

1. Only scan CVEs for images returned by graphql calls
Since pagination was refactored to account for image indexes, we had started
to run the CVE scanner before pagination was applied, resulting in
decreased ZOT performance if CVE information was requested
2. Increase in medory-cache of cve results to 1m, from 10k digests.
3. Update CVE model to use CVSS severity values in our code.
Previously we relied upon the strings returned by trivy directly,
and the sorting they implemented.
Since CVE severities are standardized, we don't need to pass around
an adapter object just for pagination and sorting purposes anymore.
This also improves our testing since we don't mock the sorting functions anymore.
4. Fix a flaky CLI test not waiting for the zot service to start.
5. Add the search build …

fix(cve): cumulative fixes and improvements for CVE scanning logic

---

pkg/api/config/config.go
pkg/api/controller.go
pkg/api/routes.go
pkg/cli/client/cve_cmd_internal_test.go
pkg/extensions/extension_search.go
pkg/extensions/extension_search_disabled.go
pkg/extensions/search/cve/cache/cache.go
pkg/extensions/search/cve/cve.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/cve/scan.go
pkg/extensions/search/cve/scan_test.go
pkg/extensions/search/cve/trivy/scanner.go
pkg/extensions/search/cve/trivy/scanner_test.go
pkg/extensions/search/cve/update.go
pkg/extensions/search/cve/update_test.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/search_test.go
pkg/meta/boltdb/boltdb.go
pkg/meta/dynamodb/dynamodb.go
pkg/meta/types/types.go
pkg/test/mocks/cve_mock.go

1. Move existing CVE DB download generator/task login under the cve package
2. Add a new CVE scanner task generator and task type to run in the background, as well as tests for it
3. Move the CVE cache in its own package
4. Add a CVE scanner methods to check if an entry is present in the cache, and to retreive the results
5. Modify the FilterTags MetaDB method to not exit on first error
This is needed in order to pass all tags to the generator,
instead of the generator stopping at the first set of invalid data
6. Integrate the new scanning task generator with the existing zot code.
7. Fix an issue where the CVE scan results for multiarch images was not cached
8. Rewrite some of the older CVE tests to use the new image-utils test package
9. Use the CVE scanner as attribute of the …

feat(cve): implement CVE scanning as background tasks

---

pkg/storage/common/common.go
pkg/storage/gc/gc.go
pkg/storage/imagestore/imagestore.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3_test.go
pkg/storage/types/types.go
pkg/test/mocks/image_store_mock.go

no need to run dedupe/restore blobs for images being pushed or synced while running dedupe task, they are already deduped/restored inline.
bug
#1843 
```release-note
```

fix(dedupe): run dedupe only for repositories found at startup

---

.github/actions/setup-localstack/action.yaml
.github/workflows/ecosystem-tools.yaml
.github/workflows/nightly.yaml

ci: update localstack to 2.3.1

---

pkg/api/errors/errors.go
pkg/api/routes.go

bug
Error codes that zot sends to clients should match https://specs.opencontainers.org/distribution-spec/?v=v1.0.0#error-codes

fix: errors returned by zot should match the dist-spec errors

---

Makefile
examples/config-policy.json
pkg/api/controller_test.go
pkg/api/errors/errors.go
pkg/extensions/extension_metrics_disabled.go
pkg/extensions/extensions_test.go
test/blackbox/anonymous_policy.bats
test/blackbox/detect_manifest_collision.bats
test/blackbox/helpers_metrics.bash
test/blackbox/helpers_zot.bash
test/blackbox/metadata.bats
test/blackbox/metrics_minimal.bats
test/blackbox/pushpull_authn.bats

bug
https://github.com/project-zot/zot/issues/1859

fix: metrics endpoint must be secured behind authN

---

pkg/cli/client/image_cmd_internal_test.go
pkg/compliance/v1_0_0/check.go
pkg/extensions/extension_ui_test.go
pkg/extensions/imagetrust/image_trust_disabled_test.go
pkg/extensions/imagetrust/image_trust_test.go
pkg/extensions/sync/sync_test.go
pkg/test/image-utils/multiarch.go

refactor(tests): Migrate some of the older tests to the new image-utils library

---

.github/workflows/nightly.yaml
CONTRIBUTING.md
Makefile
build/Dockerfile-conformance
build/Dockerfile-minimal
build/Dockerfile-zb
build/Dockerfile-zxp

build: fix container image targets

---

pkg/log/guidelines.md

docs: add logging guidelines

---

pkg/storage/cache/boltdb_test.go
pkg/storage/cache/dynamodb.go
pkg/storage/cache/dynamodb_test.go

fix(cache): make dynamoDB aware of orignal/deduped blobs

---

pkg/extensions/sync/httpclient/client.go

fix(sync): fix data race when pinging registries by read-locking

---

pkg/api/authn.go

https://github.com/project-zot/zot/issues/1914
```release-note
```

fix(authn): apply fail delay only if credentials/sessions are supplied

---

pkg/api/authn.go
pkg/api/controller_test.go

bug
https://github.com/project-zot/zot/issues/1910
```release-note
```

fix(authn): create sessions only if UI header value is supplied

---

.github/workflows/nightly.yaml
test/blackbox/helpers_zot.bash
test/blackbox/pushpull_running_dedupe.bats
test/blackbox/restore_s3_blobs.bats

change the startup dedupe blackbox test source image with a lighter one
```release-note
```

fix(nightly): increase nightly delays and timeouts

---

pkg/api/authn.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/api/cookiestore.go
pkg/storage/imagestore/imagestore.go
pkg/storage/types/types.go
pkg/test/mocks/image_store_mock.go

fix(sessions): periodically cleanup expired sessions

---

examples/config-metrics-authz.json
pkg/api/authn.go
pkg/api/authz.go
pkg/api/config/config.go
pkg/api/routes.go
pkg/extensions/README.md
pkg/extensions/extension_metrics.go
pkg/extensions/extension_metrics_disabled.go
pkg/extensions/monitoring/monitoring_test.go
pkg/test/skip/skip_test.go
test/blackbox/helpers_metrics.bash
test/blackbox/metrics.bats
test/blackbox/metrics_minimal.bats

bug
#1876
In case anonymous policy is present in access control,we allow anonymous users to access to access /metrics endpoints.
To prevent this in accessControl section of config you can specify a list of metrics users that are allowed to access /metrics endpoint.
In case accessControl is not specified in config but auth is present than only authenticated users can access /metrics endpoint
By submitting this pull request, I confirm that my …

fix: metrics should be protected behind authZ

---

pkg/storage/common/common.go
pkg/storage/common/common_test.go
pkg/storage/imagestore/imagestore.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3_test.go
pkg/storage/storage_test.go
pkg/storage/types/types.go
pkg/test/mocks/image_store_mock.go
test/gc-stress/config-gc-bench-s3-minio.json
test/gc-stress/config-gc-referrers-bench-s3-minio.json

CheckBlob() returns ErrBlobNotFound on corrupted blobs
closes #1922
```release-note
```

feat(api): repair corrupted blobs when pushed again

---

.github/workflows/build.yaml
.github/workflows/nightly.yaml
.github/workflows/test.yaml
pkg/meta/dynamodb/dynamodb.go
pkg/meta/version/version_test.go

ci: use runners provided by CNCF

---

pkg/api/authn_test.go
pkg/api/controller_test.go
pkg/api/routes_test.go
pkg/cli/client/client_test.go
pkg/cli/server/config_reloader_test.go
pkg/debug/pprof/pprof_test.go
pkg/extensions/extensions_test.go
pkg/extensions/lint/lint_test.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/userprefs_test.go
pkg/extensions/sync/sync_test.go
pkg/log/log_test.go
pkg/storage/cache_benchmark_test.go
pkg/test/common/fs.go
pkg/test/common/fs_test.go
pkg/test/common/utils.go

fix: tests refactoring

---

.github/workflows/tls.yaml
examples/config-tls.json
test/scripts/tls_scan.sh

fix: ci 'TLS check' job is broken

---

Makefile

fix: Makefile 'run' target should not depend on running tests

---

pkg/cli/client/client.go
pkg/cli/client/image_cmd_test.go
pkg/common/common.go
pkg/extensions/search/search_test.go
pkg/extensions/sync/references/oci.go
pkg/extensions/sync/references/references.go
pkg/extensions/sync/references/references_internal_test.go
pkg/extensions/sync/sync_test.go
pkg/meta/boltdb/boltdb.go
pkg/meta/dynamodb/dynamodb.go
pkg/meta/meta_test.go
pkg/meta/parse.go
pkg/meta/types/types.go
pkg/storage/common/common.go
pkg/storage/gc/gc.go
pkg/storage/local/local_test.go
pkg/storage/storage.go
pkg/test/oci-utils/oci_layout.go
pkg/test/oci-utils/oci_layout_test.go
pkg/test/signature/cosign.go
test/blackbox/annotations.bats

feat: add support for oci1.1 cosign signatures

---

pkg/storage/imagestore/imagestore.go

bug
i didn't make an issue. I can
some s3 stores will return PathNotFoundError on storeDriver.Walk but not storeDriver.List on the root directory
this adds a case to handle that  
enable "scrub" while using digitalocean spaces as your s3 provider for storageDriver. dont't specify a root directory for the storageDriver, and if the bucket is empty, you'll see a bunch of errors from the scheduled task. Note that this only happens on the main branch, not the 1.4.3 release. 
```
distSpecVersion: 1.0.1
storage:
rootDirectory: /tmp/zot
gc: false
dedupe: false
storageDriver:
name: s3
region: nyc3
regionendpoint: …
```

fix: handle pathnotfound for walk call

---

pkg/api/authn_test.go
pkg/api/routes.go

fix(routes): fix cors headers for api keys and logout route

---

Makefile

To enable building zui from forks in case of local testing

build(zui): add new makefile variables for the zui repo

---

examples/README.md

docs: update example documentation to use the current authz structure

---

examples/config-ldap-credentials.json
examples/config-ldap.json
pkg/api/authn.go
pkg/api/config/config.go
pkg/api/config/config_test.go
pkg/api/controller_test.go
pkg/api/ldap.go
pkg/cli/server/root.go
pkg/cli/server/root_test.go
pkg/extensions/extensions_test.go

feat(ldap): add option to load ldap from file

---

pkg/extensions/monitoring/monitoring_test.go
pkg/storage/common/common.go

fix: TestPopulateStorageMetrics fails occasionally in CI

---

.github/workflows/nightly.yaml
examples/kind/kind-ci.sh
examples/metrics/kubernetes/zot-extended/deployment.yaml
examples/metrics/kubernetes/zot-extended/patch-deployment.yaml
examples/metrics/kubernetes/zot-extended/servicemonitor.yaml

ci(nightly): add prometheus kind test

---

.github/workflows/ecosystem-tools.yaml

The GH runner with name ubuntu-latest is at the moment running Ubuntu 22.04, The workflow was picking the package for Ubuntu 20.04

build(workflows): make sure we install the crio package matching the correct ubuntu version

---

pkg/cli/server/root.go

fix(config): better configuration errors using viper.UnmarshalExact()

---

pkg/storage/imagestore/imagestore.go

fix(metrics): one-time tasks should not be starved

---

build/Dockerfile
build/Dockerfile-conformance
build/Dockerfile-minimal
build/Dockerfile-zb
build/Dockerfile-zxp
build/stacker-conformance.yaml
build/stacker-minimal.yaml
build/stacker-zb.yaml
build/stacker-zxp.yaml
build/stacker.yaml

See:
https://github.com/GoogleContainerTools/distroless/issues/1467
```release-note
```

ci: move distroless to debian12

---

errors/errors.go
pkg/api/authn.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/cli/client/config_cmd.go
pkg/cli/server/config_reloader.go
pkg/cli/server/extensions_test.go
pkg/cli/server/root.go
pkg/cli/server/root_test.go
pkg/compliance/v1_0_0/check.go
pkg/exporter/cli/cli.go
pkg/meta/meta.go
pkg/meta/meta_test.go
pkg/storage/cache.go
pkg/storage/cache/boltdb.go
pkg/storage/cache/boltdb_internal_test.go
pkg/storage/cache/boltdb_test.go
pkg/storage/cache/dynamodb.go
pkg/storage/cache/dynamodb_test.go
pkg/storage/cache_test.go
pkg/storage/storage.go
pkg/storage/storage_test.go

Closes #1686
```release-note
```

refactor(log): replace panics with log fatal or log panic functions

---

.github/workflows/publish.yaml

- `yq` command removes the extra spaces before an end line comment so this will cause `helm lint` failure
- by this change, the deleted spaces will be ignored and it will be kept only the new value of `.image.tag`
```release-note
```

fix(ci): prevent spaces from being removed when helm chart is updated

---

go.mod
pkg/extensions/search/cve/cve.go
pkg/extensions/search/cve/model/models.go
pkg/extensions/search/cve/trivy/scanner.go
pkg/extensions/search/cve/trivy/scanner_internal_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go

feat(cve): expand search domain to cve description and package info

---

Makefile

build(zui): add a new env to set the path to a local build of zui

---

pkg/cli/client/cve_cmd_internal_test.go
pkg/cli/client/cve_cmd_test.go
pkg/cli/client/image_cmd_internal_test.go
pkg/cli/client/image_cmd_test.go
pkg/cli/client/search_functions.go
pkg/cli/client/search_functions_internal_test.go
pkg/cli/client/service.go
pkg/common/model.go
pkg/extensions/search/convert/convert_internal_test.go
pkg/extensions/search/convert/cve.go
pkg/extensions/search/cve/cve.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/cve/model/models.go
pkg/extensions/search/cve/pagination_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/search_test.go
pkg/test/mocks/cve_mock.go

For CLI output is similar to:
```
CRITICAL 0, HIGH 1, MEDIUM 1, LOW 0, UNKNOWN 0, TOTAL 2
ID                SEVERITY  TITLE
https://github.com/advisories/GHSA-w2w6-xp88-5cvw     HIGH      openssl: Denial of service by excessive resou...
https://github.com/advisories/GHSA-77f3-6546-6rj7     MEDIUM    openssl: Invalid certificate policies in leaf...
```

feat(CVE): add CVE severity counters to returned images

---

pkg/extensions/extension_mgmt.go
pkg/extensions/extensions_test.go
swagger/docs.go
swagger/swagger.json
swagger/swagger.yaml

fix(apikey): show api key configuration in mgmt API

---

pkg/extensions/extension_ui.go

- Add new ui route "/user" to ui extension router configuration
bug
Helps close zui issue project-zot/zui#373
The new ui route implemented in zui PR project-zot/zui#403 returns 404 on refresh. Adding this in the extensions_ui file seems to fix this
```release-note
```

patch: Add user route to extension_ui.go

---

pkg/api/controller.go
pkg/cli/server/config_reloader.go
pkg/cli/server/root.go

check for nil values before stopping http server and task scheduler.
```release-note
```

fix(shutdown): fix crash when shutting down before server and task scheduler have started.

---

pkg/api/controller.go

We expect panics in the server/datapath to be few and far between. So the backtraces are more valuable now.
```release-note
```

fix: enable panic backtraces

---

pkg/api/ldap.go

We cannot assume the LDAP server will have group attributes programmed everytime. So handle it accordingly.
```release-note
```

fix: npe if ldap query doesn't return attributes

---

pkg/cli/server/root.go
pkg/cli/server/root_test.go

feat(config): handle config files with no explicit extension

---

examples/README.md

Documentation
N/A
Fix documentation to use proper field called repositories instead of repoNames. This looks like an accidental mix up with the variable name used in code vs configuration field in this change  https://github.com/project-zot/zot/pull/1866 .
None this is a documentaion change.
Nope only a documentation change.
```release-note
Fix Examples Readme to use correct field storage.retention.policies.repositories.
```
By submitting …

docs: Fix Examples Readme to use proper field `repositories` instead of `repoNames`

---

pkg/storage/imagestore/imagestore.go
pkg/storage/s3/s3_test.go
pkg/storage/scrub.go
pkg/storage/storage_test.go
pkg/storage/types/types.go
pkg/test/mocks/image_store_mock.go

instead of reading entire files before calculating their digests stream them by using their Reader method.
```release-note
```

fix: excessive memory usage

---

pkg/cli/client/gql_queries.go
pkg/extensions/search/cve/cve.go
pkg/extensions/search/cve/cve_internal_test.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/cve/model/models.go
pkg/extensions/search/cve/pagination_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go
pkg/test/mocks/cve_mock.go

feat(cve): add option to exclude string from cve search

---

test/blackbox/helpers_zot.bash
test/blackbox/pushpull_running_dedupe.bats

in this nightly test we restart zot for changing dedupe option because zot storage is already populated it will take some time to startup because of dedupe startup task which is run before starting the server.
```release-note
```

fix(nightly): increase wait time for dedupe nightly build

---

pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

Generators are now ordered by rank in the priority queue.
The rank computation formula is:
- 100/(1+generated_task_count) for high priority tasks
- 10/(1+generated_task_count) for medium priority tasks
- 1/(1+generated_task_count) for low priority tasks
Note the ranks are used when comparing generators both with the same priority and with different priority.
So now we are:
- giving an opportunity to all generators with the same priority to take turns generating tasks
- giving roughly 1 low priority and 10 medium priority tasks the opportunity to run for every 100 high priority tasks running.
After a generator generates a task, the generators are reordered in the priority queue based on rank.
By submitting this pull request, I confirm that my contribution is made under the terms of the …

fix: the scheduler is now fair

---

pkg/api/authn.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/cli/server/config_reloader.go
pkg/cli/server/root.go
pkg/extensions/sync/sync_test.go

Closes #2161
```release-note
```

feat(ldap): hot reloading ldap credentials on change

---

THIRD-PARTY-LICENSES.md
go.mod
go.sum

https://github.com/project-zot/zot/pull/2178
```release-note
```

chore: update go.mod to fix dependabot alerts

---

pkg/api/cookiestore.go
pkg/extensions/extension_scrub.go
pkg/extensions/imagetrust/image_trust.go
pkg/extensions/search/cve/scan.go
pkg/extensions/search/cve/update.go
pkg/extensions/sync/sync.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/storage/common/common.go
pkg/storage/gc/gc.go

This causes the "fair" scheduler to run it too often in the detriment of other generators. The intention was to run it every 2 hours but the measurement unit for 7200 was not specified.
Add more logs, including showing a generator name, in order to troubleshoot this kind of issues easier in the future.

fix(scheduler): the session cleanup generator is reset too often

---

test/blackbox/scrub.bats

Since the scheduler no longer executes generators in a fixed order, and scrub logic refactoring, the scrub tasks may or may not complete in the expected time. Increase sleep times used to search for tasks results in zot logs.

ci: stabilize ecosystem client tools workflow

---

.github/workflows/publish.yaml
build/multiarch-zb.json
build/multiarch-zot-minimal.json
build/multiarch-zot.json
build/multiarch-zxp.json
scripts/build_multiarch_image.sh

Example usage:
scripts/build_multiarch_image.sh --registry ghcr.io/project-zot --source-tag v2.0.0 --file build/multiarch-zot.json --destination-tags="v2.0.0 latest"

ci: add script to build/publish a zot multiarch image

---

.github/workflows/build.yaml

feature
Closes #715 
This PR adds an additional job to the `build` workflow  to generate SHA256 hashes for all the released assets and releases a checksums text file containing all the hashes.
The checksum release job only runs during a `release` event with a `publish` action.
The logical operations are:
1. Download all the release assets
2. Generate hashes for each and place into a text file
3. Release the checksum file
Tested with a tagged release on a fork:
https://github.com/vrajashkr/zot/releases/tag/1.0.2
Checked contents of hash file:
Downloaded all the files from the release into a directory and cross-checked generated hashes:
(Tested on …

ci: release a checksums file with SHA256 hashes for release assets

---

test/blackbox/helpers_scrub.bash

If the manifest is not present, scrub no longer errors, so the test looking for errors in the log was not failing.
See the related scrub changes in: https://github.com/project-zot/zot/pull/2180

test(blackbox): fix the scrub test sometimes deleting the image manifest from the layout

---

.github/workflows/nightly.yaml

ci(nightly): update go version used for prometheus tests

---

examples/README.md
pkg/api/authn.go
pkg/api/controller_test.go
pkg/api/routes.go
pkg/common/http_client.go
pkg/common/http_client_test.go
pkg/extensions/extension_sync.go
pkg/extensions/sync/httpclient/cache.go
pkg/extensions/sync/httpclient/client.go
pkg/extensions/sync/httpclient/client_internal_test.go
pkg/extensions/sync/on_demand.go
pkg/extensions/sync/remote.go
pkg/extensions/sync/service.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_test.go
pkg/test/mocks/sync_remote_mock.go

fixed ping function taking too much time
closes: #2213 #2212
bug
Fixes the sync taking too much time to fallback to serving local cached image, in case the remote is unavailable.
Added bearer auth for http client.
Should also fix multiple unauthorized messages we saw in sync logs when trying to sync referrers.
This is WIP
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

fix(sync): added bearer client for sync

---

Makefile
pkg/cli/client/cve_cmd_internal_test.go
pkg/cli/client/search_functions_internal_test.go
pkg/cli/client/service.go
pkg/extensions/search/cve/cve_internal_test.go
pkg/extensions/search/cve/model/models.go
pkg/extensions/search/cve/trivy/scanner.go
pkg/extensions/search/cve/trivy/scanner_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/schema.graphql
pkg/test/image-utils/utils.go

feature
Partially addresses #2175 
This PR has changes that includes `PackagePath` information for a CVE. This informs the user about the path where the vulnerable package can be found in their image.
Test image: https://hub.docker.com/r/fl73/spring4shell-vulnerable-app
Package information is not shown in ZLI CLI output today. However, other output formats include this data.
Command: `./bin/zli-linux-amd64 cve --config main list fl73/spring4shell-vulnerable-app:latest -f yaml`
Output:
```yaml
---
tag: latest
cvelist:
- id: CVE-2016-1000027
severity: CRITICAL
title: 'spring: HttpInvokerServiceExporter readRemoteInvocation method untrusted
java …
```

feat: Include PackagePath information in CVE results for image

---

pkg/storage/common/common_test.go
pkg/storage/local/driver.go
pkg/storage/local/driver_test.go
pkg/storage/s3/s3_test.go

Also add tests to fix some of the coverage fluctuations.

fix(npe): handle case where os.Stat returns different error types in DirExists

---

errors/errors.go
pkg/cli/client/cve_cmd_test.go
pkg/cli/client/cves_cmd.go
pkg/cli/client/cves_sub_cmd.go
pkg/cli/client/flags.go
pkg/cli/client/gql_queries.go
pkg/cli/client/image_cmd_internal_test.go
pkg/cli/client/search_functions.go
pkg/cli/client/service.go
pkg/common/model.go
pkg/extensions/search/cve/cve.go
pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/gql_generated/generated.go
pkg/extensions/search/gql_generated/models_gen.go
pkg/extensions/search/resolver.go
pkg/extensions/search/resolver_test.go
pkg/extensions/search/schema.graphql
pkg/extensions/search/schema.resolvers.go
pkg/meta/types/types.go
pkg/test/mocks/cve_mock.go

feat(cve): cli cve diff

---

pkg/cli/client/cve_cmd_internal_test.go
pkg/cli/client/search_functions.go
pkg/cli/client/search_functions_internal_test.go
pkg/cli/client/service.go

feature
Towards #2175 
This PR introduces a new verbose output for listing CVEs for a given image. In this mode, all the details of the CVE are shown in full including the CVE Description and package related details.
No, there is no expected impact to upgrades or downgrades.
Yes
```release-note
A new --verbose flag is available for users to view complete details about the CVE impacting the image. This includes the full description and a list of packages which are vulnerable to the CVE.
The verbose mode can be invoked with bin/zli-linux-amd64 --config …
```

feat: add verbose mode for cves for image listing

---

pkg/api/routes.go
pkg/meta/hooks.go
test/blackbox/annotations.bats

Manifests cat be retrieved by digest but we maintain stats based only on tags. So ignore errors if not found.
Fixes issue #2299
```release-note
```

fix: ignore metadb errors if tag not found

---

.github/workflows/benchmark.yaml
.github/workflows/branch-cov.yaml
.github/workflows/build.yaml
.github/workflows/cloc.yaml
.github/workflows/cluster.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/compare-binary-size.yaml
.github/workflows/ecosystem-tools.yaml
.github/workflows/gc-stress-test.yaml
.github/workflows/golangci-lint.yaml
.github/workflows/gqlgen.yaml
.github/workflows/license.yaml
.github/workflows/nightly.yaml
.github/workflows/oci-conformance-action.yaml
.github/workflows/sync-3rdparty-images.yaml
.github/workflows/test.yaml
.github/workflows/tls.yaml
.github/workflows/web-scan.yaml
Makefile
build/Dockerfile
build/Dockerfile-conformance
build/Dockerfile-minimal
build/Dockerfile-zb
build/Dockerfile-zxp
build/stacker-conformance.yaml
build/stacker-minimal.yaml
build/stacker-zb.yaml
build/stacker-zxp.yaml
build/stacker.yaml
go.mod

1.
Only go toolchain version is updated.
We compile with go 1.22, but we allow others to compile using language version 1.21 if they wish to. If we also updated the go version in go.mod everyone would be forced to update, as that is enforced as a minimum allowed version.
This comment explains the difference well enough https://news.ycombinator.com/item?id=36455759
2.
It looks like they made some cleanup in the logic allowing buildmode pie on various platforms.
Related to https://github.com/golang/go/issues/31544
See the code at: https://cs.opensource.google/go/go/+/master:src/internal/platform/supported.go;l=222-231;drc=d7fcb5cf80953f1d63246f1ae9defa60c5ce2d76;bpv=1;bpt=0

chore: update to go 1.22

---

.github/workflows/verify-config.yaml
Makefile
examples/README.md
examples/config-example.json
examples/config-example.yaml
pkg/cli/server/root.go
pkg/cli/server/root_test.go

Rebase and fix coverage issues in https://github.com/project-zot/zot/pull/2215.

Add a job to check zot config examples (and fix existing examples)

---

test/blackbox/pushpull_authn.bats

Both as a test and an example.
Inspired by:
https://github.com/kubeflow/model-registry/blob/main/docs/logical_model.md
```release-note
```

ci: add a ML model artifact test case

---

pkg/cli/client/cve_cmd_internal_test.go
pkg/cli/client/cve_cmd_test.go
pkg/cli/client/search_functions_internal_test.go
pkg/cli/client/service.go
pkg/cli/client/utils.go

feature
Towards #2175 
Addresses this comment: https://github.com/project-zot/zot/issues/2175#issuecomment-1979322270
This PR adds a brief listing of vulnerable packages to the CVE list view. This will give the user an overall picture of the impacted packages. It displays the name, path (if available), installed version, and fixed version.
Image with few vulnerable packages:
Image with many vulnerable packages with and without paths:
Image with smaller terminal window displaying line wrapping (Gnome terminal):
N/A
No, it is not expected to impact upgrade or downgrades as the …

feat: show brief package list in image CVE listings

---

build/stacker-conformance.yaml
build/stacker-minimal.yaml
build/stacker-zb.yaml
build/stacker-zxp.yaml
build/stacker.yaml

Fixes issue #2353
```release-note
```

ci: add description field to our published images

---

pkg/cli/server/root.go
pkg/cli/server/root_test.go

Expect exactly one positional argument for the serve command with the path to the config file.
bug
There's no reported issue AFAIK.
This PR adds a check to the `serve` command to expect exactly one positional argument with the config file path. Improving the user experience.
Running `zot serve` (without passing a config file path) results in an index out-of-range error:
```
$ ./bin/zot-darwin-arm64 serve
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
zotregistry.dev/zot/pkg/cli/server.NewServerRootCmd.newServeCmd.func2(0x14002026800?, {0x10aede5e0, 0x0, …
```

fix(cli/server): serve command expected positional args

---

.github/workflows/sync-3rdparty-images.yaml

localstack images published to dockerhub don't appear to be signed via docker content trust.
```release-note
```

chore: disable content trust check for localstack image

---

errors/errors.go
pkg/extensions/search/cve/pagination.go
pkg/extensions/search/cve/pagination_test.go

It is possible to ask for a very large limit size which can exhaust memory.
```release-note
```

fix: additional input validation for CVE graphQL query

---

pkg/api/proxy.go
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/extensions/extension_sync.go
pkg/extensions/sync/service.go
pkg/extensions/sync/sync_internal_test.go
pkg/extensions/sync/sync_test.go

feature
Closes #2420
This commit includes support for periodic repo sync in a scale-out cluster.
Before this commit, all cluster members would sync all the configured repos as the config is shared amongst all the members.
With this change, in periodic sync, the cluster member checks whether it manages the repo. If it does not manage the repo, it will skip the sync.
This commit also includes a unit test to test on-demand sync too, but there are no logic changes for it as it is implicitly handled by the proxying logic.
Covered by Unit Tests
N/A
No
**Does this PR introduce any …

feat(sync): support for periodic repo sync in scale-out cluster

---

.github/workflows/ecosystem-tools.yaml
pkg/storage/imagestore/imagestore.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3_test.go

remove unnecessary calls to storage driver

---

pkg/extensions/search/resolver.go
pkg/meta/dynamodb/dynamodb_test.go

when a UI client tries to view image details
for an image with multiple tags pointing to the same digest we make a query to dynamodb having duplicate keys (same digest) resulting in an error and the client is redirect back to image overview.
closes: #2464
```release-note
```

fix(ui): fix image details view

---

pkg/api/config/config.go
pkg/api/routes.go
pkg/storage/imagestore/imagestore.go

fix(storage): handle dedupe disabled in GetAllDedupeReposCandidates()

---

errors/errors.go
pkg/extensions/sync/destination.go
pkg/extensions/sync/oci_layout.go
pkg/extensions/sync/service.go
pkg/extensions/sync/sync_internal_test.go

bug
closes https://github.com/project-zot/zot/issues/2527
It does two very small things.
First: it ensures that Zot doesn't panic with a nil pointer dereference on incorrectly configured local storage in the sync extension, and instead returns an error when `localImageStore` is nil.
Second: (and arguably more important) it enables logging for the sync extension image store.
I have manually tested this on my cluster, and can confirm that logging accurately shows my configuration error in #2527 (I had configured Zot to use a read-only filesystem, which obviously …

Fix sync extension logging

---

pkg/api/controller_test.go
pkg/storage/common/common.go
pkg/storage/common/common_test.go
pkg/storage/gc/gc.go
pkg/storage/gc/gc_internal_test.go
pkg/storage/imagestore/imagestore.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3_test.go
pkg/storage/storage_test.go
pkg/storage/types/types.go
pkg/test/image-utils/images.go
pkg/test/image-utils/multiarch.go
pkg/test/image-utils/upload.go
pkg/test/image-utils/write.go
pkg/test/mocks/image_store_mock.go

fix(digests): do not mandate sha256 as the only algorithm used for hashing blobs

---

.github/workflows/golangci-lint.yaml
.github/workflows/test.yaml

CNCF has been nice to us to offer larger runners, but we need to be careful not to abuse them.
```release-note
```

ci: use smaller runners for CI pipelines

---

pkg/api/session.go
pkg/cli/client/client.go
pkg/cli/client/utils_internal_test.go
pkg/meta/convert/convert.go
pkg/meta/convert/convert_proto.go

Originally found by @jkroepke in: https://github.com/project-zot/zot/actions/runs/10056774230/job/27796324933?pr=2556 And https://github.com/project-zot/zot/pull/2556 in general
This commit covers:
- (canonicalheader) capitalization of Docker-Content-Digest header
- (protogetter) the proto getters were not used, they check for nil pointers, we should switch to using them
- (zerologlint) fix the false positive

fix: various lint issues

---

pkg/storage/gc/gc.go
pkg/storage/gc/gc_test.go
pkg/storage/imagestore/imagestore.go
pkg/storage/local/local_test.go
pkg/storage/types/types.go
pkg/test/mocks/image_store_mock.go

fix(gc): gc now removes blob uploads which have not changed within the gc delay interval

---

examples/README.md
examples/config-openid.json
examples/sessionKeys.json
pkg/api/authn.go
pkg/api/authn_test.go
pkg/api/config/config.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/api/cookiestore.go
pkg/cli/server/root.go
pkg/cli/server/root_test.go

If they are not configured zot will generate a random hashing key at startup, invalidating all cookies if zot is restarted. closes: #2526
bug
restarting zot invalidates currently active sessions.
https://github.com/project-zot/zot/issues/2526
no
```release-note
modified configuration file, client can specify hashing and encrypt keys to secure web session cookies.
```
By submitting this pull request, I confirm that my contribution is made …

fix(authn): make hashing/encryption keys used to secure cookies

---

.github/workflows/codeql-analysis.yml
.github/workflows/publish.yaml
.github/workflows/scorecards.yaml
go.mod
go.sum

https://github.com/project-zot/zot/pull/2622
https://github.com/project-zot/zot/pull/2623
```release-note
```

chore: fix dependabot alerts

---

pkg/meta/dynamodb/dynamodb.go

Fixes issue #2627
We get/put metadata in dynamodb and it appears there are limits enforced by AWS S3 APIs.
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html
If you request more than 100 items, BatchGetItem returns a ValidationException with the message "Too many items requested for the BatchGetItem call."
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the …

fix: work around AWS S3 limits

---

cmd/zb/helper.go
pkg/api/controller_test.go
pkg/storage/common/common.go
pkg/storage/imagestore/imagestore.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3_test.go

In case of delete by tag only the tag is removed, the manifest itself would continue to be accessible by digest. In case of delete by digest the manifest would be completely removed (provided it is not used by an index or another reference).

fix(delete manifest): distinct behaviors for delete by tag vb delete by digest

---

pkg/storage/imagestore/imagestore.go

https://github.com/project-zot/zot/issues/2596
```release-note
```

fix(metrics): update storage metrics on gc

---

pkg/storage/imagestore/imagestore.go

cache.HasBlob() looks in both buckets: duplicates and original blobs Because we want to check if the blob is in original bucket let's use cache.GetBlob() because it's looking only in original bucket.
```release-note
```

fix(s3): fix check in dedupe logic

---

pkg/meta/dynamodb/dynamodb.go

bug fix
Fix zot unable to create dynamodb table. Upon starting zot with `cacheDriver` configured to dynamodb. Zot will panic with error `exceeded max wait time for TableExists waiter`.
Dynamodb table is successfully created but not seeded with Zot version
Zot was unable to wait for dynamodb table to be created. This was due to `maxWaitTime` set too low. More to be reference on AWS SDK issue https://github.com/aws/aws-sdk-go-v2/issues/2551
no
no
By submitting this pull request, I confirm that my contribution is made under the …

fix: max wait time on dynamodb

---

pkg/extensions/search/cve/cve_test.go
pkg/extensions/search/resolver.go
pkg/extensions/search/search_test.go
pkg/meta/boltdb/boltdb.go
pkg/meta/dynamodb/dynamodb.go

Also fix an issue with searching tags, which should work with case insensitive searches.

fix: issues with nested index processing in CVE and metaDB code

---

pkg/storage/common/common.go

chore: less confusing warning message when unexpected media type is found in index manifest list

---

pkg/cli/server/root.go

See #2744, there are 2 updates:
1. Silence the usage output in case of config verification errors
2. Wrap the error details in all of the zot configuration errors so they are propagated and shown in stdout for `zot verify` We also need to keep logging those message to the zot logs file since the same logic is called in the `zot serve` use case.

fix: improve output of zot verify

---

pkg/extensions/sync/httpclient/client.go

bug
https://github.com/project-zot/zot/issues/2557
Note: I haven't managed to run a full `make` yet, my Mac seems to not play nice with `golangci-lint` and starts leaking memory heavily :)
I spun up a local instance of zot (with locally built images) and an 'upstream' repository with HTTPS enabled using a self-signed certificate with the following `docker-compose.yml`:
```yaml
services:
zot:
image: localhost/project-zot/zot-linux-arm64:fixed
ports:
- "8080:5000"
volumes:
- ./config.json:/etc/zot/config.json:ro
- zot_data:/var/lib/registry
registry:
image: …
```

fix: enable TLS based on URL scheme for sync extension

---

.github/workflows/sync-3rdparty-images.yaml
pkg/cli/server/extensions_test.go
pkg/extensions/search/cve/trivy/scanner_internal_test.go
pkg/extensions/search/cve/trivy/scanner_test.go

This is to avoid errors such as:
```
Error: failed to resolve latest: GET "https://ghcr.io/v2/aquasecurity/trivy-db/manifests/latest": response status code 429: toomanyrequests: retry-after: 338.733µs, allowed: 44000/minute
```
or
```
Error: GET "https://ghcr.io/v2/aquasecurity/trivy-java-db/blobs/sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a": response status code 429: toomanyrequests: retry-after: 271.886µs, allowed: 44000/minute
```
There are 2 remaining exceptions that I am aware of:
1. The tests under test/blackbox/cve.bats
2. One of the cli tests checking the server attempts download of the databases from the default url

chore: update go tests to use our hosted trivy-db and trivy-java-db images

---

.github/workflows/publish.yaml

https://github.com/project-zot/helm-charts/issues/47
```release-note
```

fix: prevent releases of helm chart with pre-releases of zot

---

build/Dockerfile
build/Dockerfile-conformance
build/Dockerfile-minimal
build/Dockerfile-zb
build/Dockerfile-zxp
build/stacker-conformance.yaml
build/stacker-minimal.yaml
build/stacker-zb.yaml
build/stacker-zxp.yaml
build/stacker.yaml
test/blackbox/restore_s3_blobs.bats

There is also this issue with the dedupe tests which should not have failed according to the logs:
```
```

chore: use go1.23 in the build environment of zot container images

---

pkg/api/authz.go
pkg/api/controller_test.go
pkg/api/routes.go
pkg/api/routes_test.go
pkg/extensions/sync/httpclient/client.go
pkg/extensions/sync/references/cosign.go
pkg/extensions/sync/references/oci.go
pkg/extensions/sync/references/references.go
pkg/extensions/sync/references/referrers_tag.go
pkg/extensions/sync/remote.go
pkg/storage/imagestore/imagestore.go
pkg/storage/storage_controller.go
pkg/storage/storage_test.go
pkg/storage/types/types.go
pkg/test/mocks/image_store_mock.go
test/blackbox/pushpull.bats

Catalog content discovery

---

pkg/extensions/extension_ui.go
test/blackbox/annotations.bats

fix(headers): set Cross-Origin-Resource-Policy header for UI requests

---

errors/errors.go
pkg/meta/boltdb/boltdb.go
pkg/meta/dynamodb/dynamodb.go

1. dynamodb: refactor multiple apikey metadb calls into a single one
2. dynamodb/boltdb: fix an error message related to getting the patches to update the db (as a note this is not used atm in production)

minor metadb fixes for dynamo and bolt

---

examples/config-ratelimit.json

Some fields are mixed case which is inconsistent with the rest of example configs.
```release-note
```

docs: fix ratelimit example

---

pkg/meta/dynamodb/dynamodb.go

fix(dynamodb): properly handle ResourceInUseException for existing tables

---

examples/config-sync-ecr-credential-helper.json
go.mod
pkg/extensions/config/sync/config.go
pkg/extensions/sync/ecr_credential_helper.go
pkg/extensions/sync/remote.go
pkg/extensions/sync/service.go
pkg/extensions/sync/sync.go
pkg/extensions/sync/sync_test.go
pkg/test/mocks/sync_remote_mock.go

feature
https://github.com/project-zot/zot/issues/2650
This PR adds support for temporary credentials for upstream registries, specifically focusing on AWS ECR. Since ECR credentials are not permanent and need to be rotated periodically, this enhancement enables Zot to dynamically obtain and refresh valid usernames and passwords when the CredentialHelper is configured for the registry
N/A
During initialization, the logs confirm that ECR credentials have been updated:
```
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:77"," …
```

[Feat]: Support for AWS ECR Authentication with Temporary Tokens

---

examples/config-sync.json
pkg/cli/server/root.go
pkg/extensions/config/sync/config.go
pkg/extensions/sync/content.go
pkg/extensions/sync/content_internal_test.go

feature
Fix #2902
```release-note
```

feat(sync): add tag excludeRegex filter

---

errors/errors.go
pkg/extensions/sync/httpclient/client.go

fix(sync): fixed harbor authentication issues on _catalog endpoint

---

examples/config-ldap.json
pkg/api/authn.go
pkg/api/config/config.go
pkg/api/controller_test.go
pkg/api/ldap.go

feature
Fix #2924
```release-note
```

feat(ldap): allow to customize user filter

---

pkg/compat/compat.go
pkg/extensions/search/cve/cve.go
pkg/extensions/search/search_test.go
pkg/meta/hooks.go
pkg/meta/parse.go

- update download counters for docker media types - closes #2929
- handle docker config media type in MetaDB - The OS/Arch/Layer History information was not written to MetaDB

MetaDB fixes related to Docker media types

---

errors/errors.go
go.mod
pkg/api/authn.go
pkg/api/bearer.go
pkg/api/bearer_test.go
pkg/api/controller_test.go
pkg/extensions/extensions_test.go
pkg/extensions/sync/sync_test.go
pkg/test/auth/bearer.go
pkg/test/auth/bearer_test.go
test/scripts/gen_certs.sh

feature
https://github.com/project-zot/zot/issues/2587
Currently the `github.com/chartmuseum/auth` package is used for token authentication, which [only supports RSA keys](https://github.com/chartmuseum/auth/blob/2d81aa85f9fbc574ca7849526c7b6818880e269b/token.go#L93-L94). It also doesn't seem to be updated anymore, and uses a pretty [old version of the `golang-jwt` package](https://github.com/chartmuseum/auth/blob/2d81aa85f9fbc574ca7849526c7b6818880e269b/go.mod#L6) which could use a bump.
I have ripped out the important bits and re-implemented the token handling directly using `golang-jwt`, which allows it to support EC/ED25519 keys as well as RSA keys.
**Testing done on this …

[feat]: add support for EC/ED25519 public keys for token authentication

---

.github/workflows/cluster.yaml
pkg/meta/boltdb/boltdb.go
pkg/meta/convert/convert.go
pkg/meta/dynamodb/dynamodb.go
pkg/meta/redis/redis.go

Including handling indexes / manifest lists for buildkit manifest lists containing image cache
See
- https://github.com/project-zot/zui/issues/475
- https://github.com/project-zot/zot/issues/3000#issuecomment-2709031927
Fix and unrelated issue with killing zot and collecting logs in case of cluster test failures

fix: show data from docker mediatypes in search results

---

pkg/api/controller_test.go
pkg/storage/common/common.go
pkg/storage/s3/s3_test.go

Fixes #3005
Previously, changing a image's media-type was disallowed. However, "docker buildx" appears to first push an image manifest and then an image index for the same image tag. So, allow this.
```release-note
```

fix: allow changing media-type when pushing an image tag

---

build/Dockerfile
build/Dockerfile-conformance
build/Dockerfile-minimal
build/stacker-conformance.yaml
build/stacker-minimal.yaml
build/stacker.yaml

cleanup
PR was requested: https://github.com/project-zot/zot/discussions/3020#discussioncomment-12492398
Context for prior PRs that introduced `VOLUME`:
- `Dockerfile` originally introduced `VOLUME` in 2020: https://github.com/project-zot/zot/pull/64
- `stacker.yaml` originally introduced `volume` in 2022: https://github.com/project-zot/zot/pull/499
`VOLUME` is an old instruction that creates an implicit anonymous volume when starting a container.
- Today this implicit volume often has minimal benefits to improving performance and can be prone to causing more problems than good.
- When `VOLUME` was introduced into images for `zot`, there was no demand requesting it, nor any issue …

chore: Remove `VOLUME` instruction from image

---

pkg/api/routes.go
pkg/api/routes_test.go

bug
I tried to integrate Microsoft Entra as an OIDC provider. Entra is not returning the groups claim in the userinfo endpoint (see https://learn.microsoft.com/en-us/entra/identity-platform/userinfo).
This PR makes the OpenIDCodeExchangeCallback groups claim extraction compatible with Microsoft Entra. The groups claim from the IDTokenClaims is extracted and merged with the groups claim of the userinfo endpoint response.
Configure an Entra application as OIDC Provider. Zot is not able to find the groups claim.
```
{"level":"info","goroutine":881,"caller":"zotregistry.dev/zot/pkg/api/routes.go:1996", …
```

fix: get groups claim from idtokenclaims

---

errors/errors.go
pkg/api/authn.go
pkg/api/controller_test.go
test/scripts/gen_certs.sh

bug
https://github.com/project-zot/zot/issues/3173
Added automated test cases to check whether supplying RSA/ED/EC public keys instead of certificates works as expected.
Additionally, I spun up a local Zot instance and handed it an RSA public key (not a certificate), and verified that bearer authentication works as expected.
Nope.
```release-note
```

fix: parse public key as fallback for certificate for bearer authentication

---

pkg/retention/candidate.go
pkg/retention/retention.go
pkg/retention/types/types.go
pkg/storage/gc/gc.go
pkg/storage/gc/gc_test.go

It is to fix #3185.
This fixes the case where MetaDB is not instantiated (none of the conditions match), and we want to retain tags only by pattern (which should not need to use MetaBD).
Without this fix you could only use retention to delete untagged manifests. If you specified only the key "patterns" under "keepTags", zot would crash. It was possible to not specify "keepTags" all, which would retain all tags, but it was not possible to retains specific tags.
Basically the case quoted below, from the documentation, was broken:: https://zotregistry.dev/v2.1.4/articles/retention/#configuration-example
```
When you specify a regex pattern with no rules other than the default, all tags matching the pattern are retained.
```
This would only work if MetaDb was instantiated by an unrelated …

fix: image retention policy to handle patterns even if metadb is not instantiated

---

pkg/extensions/extension_scrub.go
pkg/extensions/monitoring/monitoring_test.go
pkg/storage/common/common.go
pkg/storage/gc/gc.go
pkg/storage/gc/gc_test.go
pkg/storage/imagestore/imagestore.go
pkg/storage/local/local_test.go
pkg/storage/s3/s3_test.go
pkg/storage/types/types.go
pkg/test/mocks/image_store_mock.go

Using just the last repository is not enough as in the case when it is deleted (either by GC or some other way), GetNextRepository returns empty string causing the generator to be marked completed without any errors.
An alternative would have been to start over from the first repository, but this can take hours if multiple repositories need to be deleted, not to mention the processing power and I/O and S3 load this could take.

fix: GetNextRepository to use a list already scanned repositories as input

---

Makefile
pkg/api/runtime.go
pkg/cli/server/stress_test.go
pkg/test/common/rlimit_freebsd.go
pkg/test/common/rlimit_linux.go

cleanup
#3246 
Allows building zot on a FreeBSD host. Not strictly needed since FreeBSD binaries can be cross-built on a Linux host but it is convenient for developers who prefer to use FreeBSD where possible.
Run 'gmake' on a host running FreeBSD-14.3.

Fix building zot natively on FreeBSD

---

pkg/storage/imagestore/imagestore.go
pkg/storage/storage_test.go

https://github.com/regclient/regclient/issues/961
https://github.com/opencontainers/distribution-spec/pull/581
Previously, zot returned the size of the currently uploaded chunk. Other registries the size of the entire blob.
Align with the latter behavior.
```release-note
```

fix: return the entire blob size in patch upload response

---

.github/workflows/benchmark.yaml
.github/workflows/ecosystem-tools.yaml
.github/workflows/gc-stress-test.yaml
.github/workflows/nightly.yaml
.github/workflows/test.yaml

chore
**Which issue does this PR fix?**:
N/A
CNCF has hosted ephemeral GitHub runners on Oracle that we want projects to use instead of the GitHub-hosted ones, which now incur a cost to use.
Please direct any questions to me, @jeefy, @krook, and @RobertKielty. You can also join `#cncf-ci-infra` channel on CNCF Slack.
**If an issue # is not available, please add repro steps and logs showing the issue**:
N/A
N/A
N/A
No
No

chore(ci): update github runners to oci gh arc runners

---

pkg/storage/gc/gc.go
pkg/storage/gc/gc_test.go
pkg/test/image-utils/images.go
pkg/test/image-utils/images_test.go
pkg/test/image-utils/multiarch.go
pkg/test/image-utils/write.go

bug
- fixes #3347: removeUntaggedManifests() did not consider compatible manifest types
- check for compatible manifest types in removeUntaggedManifests()
see #3347 
- extend TestGarbageCollectAndRetentionMetaDB to test docker image and multiarch image
- add AsDockerImage() to Image and MultiarchImage for testing
n/a
no
yes
```release-note
Image GC now considers images using docker manifests.
```
By submitting this pull request, I confirm …

fix: gc for untagged docker manifests

---

pkg/extensions/sync/service.go
pkg/log/log.go

feature
N/A
It provides, I hope, minimal Zot logger (Zerolog logger) handler for slog and enables logging for regclient with it.
N/A
N/A
N/A
N/A
N/A

feat(sync): enable regclient logs

---

.github/workflows/ecosystem-tools.yaml
examples/README.md
examples/config-remote-session-store-redis.json
go.mod
go.sum
pkg/api/authn_test.go
pkg/api/config/config.go
pkg/api/config/redis/redis.go
pkg/api/controller.go
pkg/api/controller_test.go
pkg/api/cookiestore.go
pkg/cli/server/root.go
pkg/cli/server/root_test.go
test/blackbox/ci.sh
test/blackbox/redis_session_store.bats
test/ports.json

feature
Towards #3333 
- Adds support for Redis to be used as a remote storage for session information.
- Sessions are stored in Redis and get invalidated when the user logs out on the browser or after expiry.
- Allows session information to persist outside of the Zot instance for use cases where Zot is fully stateless or there are multiple Zot instances running.
A local redis 8 container is used for this testing. The container has been started and `valkey-cli` is used to access and read the entries to verify behavior.
The test config for zot is the file `examples/config-remote-session-store-redis.json`
A login is initiated through ZUI on browser. A …

feat(sessions): add support for remote redis session store
