README.md, pkg/api/BUILD.bazel, pkg/api/routes.go, pkg/cli/BUILD.bazel, pkg/cli/root.go, pkg/compliance/BUILD.bazel, pkg/compliance/config.go, pkg/compliance/v1_0_0/BUILD.bazel, pkg/compliance/v1_0_0/check.go, pkg/compliance/v1_0_0/check_test.go
make
bin/zot compliance -H hostIP -P port -V all
This is an initial commit.
The neat thing is the same unit test code is driven by go tests and compliance cli.
=> compliance: initial commit

pkg/api/controller_test.go, test/data/htpasswd
=> test/data: remove htpasswd file

README.md, pkg/api/controller.go, pkg/api/regexp.go, pkg/api/routes.go, pkg/compliance/config.go, pkg/compliance/v1_0_0/check.go
There are two separate commits for this PR and they have their own verbose commit msgs.
=> Compliance cleanup

pkg/api/routes.go
We have noticed that very intermittently zot returns a 500 when copying
blob data. This is likely happening due to a io.ErrShortWrite
=> routes: improve error handling when returning blob data

pkg/compliance/v1_0_0/check.go
Pls. see: https://github.com/opencontainers/distribution-spec/issues/79
=> compliance: "Location" header can be absolute or relative

README.md
Documented results/notes for zot and docker.
Setting up quay is proving a little harder, will append once available.
=> README: update compliance test results

pkg/api/auth.go
We are noticing that LDAP connectivity issues and timeouts can affect
authN behavior from client side (which can timeout as well).
Instead, put local authN first so at least we have a reliable authN
method.
But, the caveat is that it is best if the local and LDAP user list
doesn't overlap.
=> authN: first try local htpasswd then LDAP

pkg/api/auth.go, pkg/api/errors.go, pkg/api/routes.go, pkg/compliance/v1_0_0/check.go, pkg/storage/storage.go, pkg/storage/storage_test.go
•HTML report was created: /home/rchincha/go/src/github.com/opencontainers/distribution-spec/conformance/report.html
JUnit report was created: /home/rchincha/go/src/github.com/opencontainers/distribution-spec/conformance/junit.xml
Ran 28 of 28 Specs in 0.099 seconds
SUCCESS! -- 28 Passed | 0 Failed | 0 Pending | 0 Skipped
=> fix compliance

WORKSPACE, go.mod, go.sum, pkg/api/auth.go, pkg/api/controller_test.go
Resolves #71
Signed-off-by: Peter Engelbert <pmengelbert@gmail.com>
=> Fix auth scope on endpoints without repo name

.bazel/golangcilint.yaml, pkg/api/routes.go, pkg/compliance/v1_0_0/check.go, pkg/storage/storage.go
---
Ran 27 of 27 Specs in 0.120 seconds
SUCCESS! -- 27 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
---
=> conformance: fix error msg for DELETE MANIFEST

examples/config-conformance.json, pkg/api/config.go, pkg/api/controller.go, pkg/api/routes.go, pkg/compliance/v1_0_0/check.go, pkg/storage/cache.go, pkg/storage/storage.go, pkg/storage/storage_test.go
Upstream conformance tests are being updated, so we need to align along
with our internal GC and dedupe features.
=> conformance: align with upstream conformance tests

README.md
Signed-off-by: Ravi Chamarthy <ravchama@cisco.com>
=> fix the conformance link

.travis.yml
zot trivy extensions test code needs an oci layout as test data.
Install skopeo to help with that.
=> ci/cd: install skopeo

.travis.yml, Dockerfile, Dockerfile.build, Makefile, stacker.yaml
Update docker and stacker builds
=> build: update docker and stacker files

MAINTAINERS.md
=> Add a MAINTAINERS.md

CONTRIBUTING.md, README.md
=> docs: add a CONTRIBUTING.md

pkg/api/controller.go
Set idle timeout value to 15 minutes 
@rchincha please let me know if we want it to be changed.
=> server: add idle timeout in http server configuration

Makefile, pkg/api/config.go, pkg/cli/root.go
``` 
{"level":"info","distribution-spec":"0.1.0-dev","commit":"extended-v1.1.12-21-gfaf4ad8-dirty","time":"2021-02-12T17:00:14-08:00","message":"version"}
``` 
``` 
{"level":"info","distribution-spec":"0.1.0-dev","commit":"minimal-v1.1.13-2-g873801e","time":"2021-02-12T17:01:34-08:00","message":"version"}
```
=> Add binary type in binary information

pkg/api/controller.go
Add support for adding some default headers, CORS in this initial commit.
(experimental patch only)
=> controller: add default headers

pkg/api/routes.go
=> routes: ignore media-type for PatchBlobUpload

.github/workflows/publish-docker-image.yml, .travis.yml
to github's container registry, closes #188
=> ci/cd: build and push zot container images

examples/config-cve.json, examples/config-multiple-cve.json, pkg/api/routes.go, pkg/cli/client.go, pkg/cli/cve_cmd.go, pkg/cli/cve_cmd_test.go, pkg/cli/image_cmd.go, pkg/cli/image_cmd_test.go, pkg/cli/searcher.go, pkg/cli/service.go, pkg/extensions/config.go, pkg/extensions/extensions.go, pkg/extensions/minimal.go, pkg/extensions/search/common/oci_layout.go, pkg/extensions/search/cve/cve.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/models.go, pkg/extensions/search/digest/digest.go, pkg/extensions/search/digest/digest_test.go, pkg/extensions/search/generated.go, pkg/extensions/search/models_gen.go, pkg/extensions/search/resolver.go, pkg/extensions/search/schema.graphql
```
Usage:
zot images [config-name] [flags]
Flags:
-d, --digest string   List images containing a specific manifest, config, or layer digest
[...]
```
Resolves #175
=> Implement a way to search for an image by manifest, config or layer digest

.github/workflows/ci-cd.yml, Dockerfile-minimal
=> ci/cd: build a "minimal" container image

.github/workflows/ci-cd.yml
=> ci/cd: fix github workflow for "minimal" image

errors/errors.go, go.mod, go.sum, pkg/storage/cache.go, pkg/storage/cache_test.go, pkg/storage/storage.go, pkg/storage/storage_test.go
- dedupe: stat blob path before creating link
=> cache fixes

pkg/storage/storage.go, pkg/storage/storage_test.go
=> pkg/storage: fix partially initialized repo storage

README.md, pkg/compliance/v1_0_0/check.go, pkg/storage/storage.go, pkg/storage/storage_test.go
- Added image deletion by tag feature.
=> api: implement delete by tag

README.md, docs/docs.go, examples/README.md, examples/config-minimal.json, examples/config-policy.json, go.mod, go.sum, pkg/api/authn.go, pkg/api/authz.go, pkg/api/config.go, pkg/api/controller_test.go, pkg/api/routes.go, pkg/cli/root.go, pkg/cli/root_test.go
Hello guys, what do you say about this structure for authorization config?
#51
=> add identity-based access control

go.mod, go.sum
There is a performance regression in umoci [1] which is fixed in [2].
References:
[1] https://github.com/opencontainers/umoci/issues/373
[2] https://github.com/opencontainers/umoci/pull/375
=> go.mod: update umoci dep

COMPARISON.md, README.md
=> doc: add documentation for comparison with well-known registries

Dockerfile-conformance, go.mod, go.sum
=> go.mod: update deps to address dependabot alerts

go.mod, go.sum
https://github.com/advisories/GHSA-c2h3-6mxw-7mvq
=> go.mod: update go.mod to fix dependabot alert

.github/workflows/release.yml
=> release: add github action to automatically generate changelog

README.md
=> ci/cd: update badges link to refer to main branch

go.mod, go.sum
Fix GHSA-77vh-xpmg-72qh
Fix GHSA-5j5w-g665-5m35
=> dependabot: fix dependabot alerts

pkg/api/routes.go
https://oras.land/implementors/
=> routes: fix CheckManifest to return content length

.github/workflows/ci-cd.yml, Dockerfile-arch, Dockerfile-arch-minimal, Dockerfile-minimal, Makefile
Addresses https://github.com/anuvu/zot/issues/294
=> ci/cd: build for arm64 arch

pkg/api/controller.go, pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_test.go, pkg/extensions/sync/utils.go
=> sync: allow for saving to a subpath, closes #307

Makefile, README.md, pkg/cli/root.go
=> build: fix build artifacts in binary

go.mod, go.sum
=> fix Dependabot alert about GHSA-v95c-p5hm-xq8f

.github/workflows/ci-cd.yml
=> ci/cd: fix arch builds to pick correct file

pkg/api/controller_test.go
cleanup
Replaces numerals with mnemonics.
=> lint: some more linter-related cleanup

go.mod, go.sum, golangcilint.yaml
update containerd version
bug
352
update go.mod entry.
=> go.mod: fix GHSA-mvff-h3cj-wj9c

.github/workflows/ci-cd.yml, Makefile, cmd/zli/main.go, cmd/zli/main_test.go, errors/errors.go, pkg/cli/config_cmd.go, pkg/cli/cve_cmd.go, pkg/cli/image_cmd.go, pkg/cli/root.go, pkg/cli/root_test.go
zot: registry server
zli: zot cli to interact with the zot registry
zui: zot ui (proposed)
zb: zot benchmark (proposed)
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> build: split functionality into separate binaries

.github/workflows/license.yaml, Makefile
feature
Enforces license checks using go-licenses
To ensure we don't link against forbidden licenses.
```
=> ci/cd: add a license checker

pkg/api/controller_test.go, pkg/api/routes.go, pkg/storage/s3/storage.go, pkg/storage/storage.go, pkg/storage/storage_fs.go
'notation list' doesn't return digests
=> notaryv2: fix 'notation list'

.github/workflows/ci-cd.yml, Dockerfile-arch-zb, Dockerfile-zb, cmd/zb/README.md, cmd/zb/perf.go, pkg/api/controller_test.go, pkg/cli/client_test.go, pkg/cli/cve_cmd_test.go, pkg/cli/image_cmd_test.go, pkg/cli/root_test.go, pkg/compliance/v1_0_0/check.go, pkg/compliance/v1_0_0/check_test.go, pkg/exporter/api/controller_test.go, pkg/extensions/monitoring/monitoring_test.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/digest/digest_test.go, pkg/extensions/sync/sync_internal_test.go, pkg/extensions/sync/sync_test.go, pkg/log/log_test.go, pkg/storage/storage_fs.go, pkg/storage/storage_fs_test.go, pkg/storage/storage_test.go, pkg/test/common.go, pkg/test/common_test.go
=> bench: fix test data

.github/workflows/ecosystem-tools.yaml, Makefile, pkg/storage/storage_fs.go
feature ci/cd
fixes oras artifacts support (validated with `oras`)
Independently verify that eco-system tools work with every release
=> ci/cd: add a basic push-pull testing using client tools

.github/workflows/ci-cd.yml, Makefile
=> ci/cd: fix build/test workflow

pkg/api/controller_test.go
adds more unit tests
increases code coverage
=> coverage: improve code coverage

.gitignore, examples/README.md, examples/config-allextensions.json, examples/config-sync.json, pkg/api/controller.go, pkg/api/routes.go, pkg/cli/cve_cmd_test.go, pkg/cli/extensions_test.go, pkg/cli/image_cmd_test.go, pkg/cli/root.go, pkg/exporter/api/controller_test.go, pkg/extensions/config/config.go, pkg/extensions/extensions.go, pkg/extensions/monitoring/monitoring_test.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/digest/digest_test.go, pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_test.go
Signed-off-by: Alexei Dodon <adodon@cisco.com>
Which issue does this PR fix: #258
=> Added config enable=true/false for extensions closes #258

pkg/api/controller_test.go
bug
Recently added ldap unit tests could cause intermittent failures.
=> test: fix ldap unit tests

.github/workflows/cloc.yml
ci/cd feature
Keeps track of lines of code in the project.
=> ci/cd: count lines of code

pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_internal_test.go, pkg/extensions/sync/sync_test.go, pkg/extensions/sync/utils.go
=> sync: pull only missing images, not everything, closes #335

examples/config-gc.json, pkg/api/config/config.go, pkg/api/controller.go, pkg/cli/root.go, pkg/cli/root_test.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/digest/digest_test.go, pkg/extensions/sync/sync_internal_test.go, pkg/extensions/sync/sync_test.go, pkg/extensions/sync/utils.go, pkg/storage/s3/s3_test.go, pkg/storage/s3/storage.go, pkg/storage/scrub_test.go, pkg/storage/storage.go, pkg/storage/storage_fs.go, pkg/storage/storage_fs_test.go, pkg/storage/storage_test.go
=> gc: add a gcDelay param

.github/workflows/stale.yaml
ci/cd feature
Helps in housekeeping and keeping PRs and issues under control.
=> ci/cd: add a workflow to detect/close stale PRs and issues

.github/workflows/ci-cd.yml
=> codecov: upgrade from v1 to v2

.github/workflows/ci-cd.yml, Makefile
Signed-off-by: Laurentiu Niculae [niculae.laurentiu1@gmail.com](mailto:niculae.laurentiu1@gmail.com)
[Issue #138](https://github.com/project-zot/zot/issues/138)
```release-note
```
=> Root access for skopeo in Makefile

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md
cleanup
We used a PR/issue template from a different project but this needs some cleanup for our own project.
=> fix issue and PR templates

go.mod, go.sum
cleanup
Move zot-specific deps under project-zot repo
```release-note
```
=> move module deps under project-zot repo

examples/config-allextensions.json, examples/config-scrub.json, pkg/api/controller.go, pkg/cli/extensions_test.go, pkg/cli/root.go, pkg/extensions/config/config.go, pkg/extensions/extensions.go, pkg/extensions/minimal.go, pkg/extensions/scrub/scrub.go, pkg/extensions/scrub/scrub_test.go, pkg/storage/scrub.go
=> make scrub inline and periodic

THIRD-PARTY-LICENSES.md
=> update 3rd party licenses

Makefile, examples/config-example.yaml, pkg/cli/root.go, pkg/cli/root_test.go
[Issue #486 ](https://github.com/project-zot/zot/issues/486)
Closes #486 
```release-note
```
=> "make verify-config" target reports issues

pkg/storage/s3/s3_test.go, pkg/storage/s3/storage.go
=> s3: fix initRepo not creating index.json in some edge cases

examples/config-gc-periodic.json, pkg/api/config/config.go, pkg/api/controller.go, pkg/api/controller_test.go, pkg/cli/root.go, pkg/cli/root_test.go, pkg/storage/s3/storage.go, pkg/storage/storage.go, pkg/storage/storage_fs.go, pkg/storage/storage_fs_test.go
=> gc: make garbage-collect periodic

go.mod, go.sum
Fixes https://github.com/project-zot/zot/security/dependabot/12
bug
https://github.com/project-zot/zot/security/dependabot/12
security fix
=> build(deps): bump github.com/swaggo/http-swagger from 1.2.5 to 1.2.6

.github/workflows/ci-cd.yml, .github/workflows/codeql-analysis.yml
cleanup
updates github workflow
older v1 action is being deprecated.
=> codeql: move from v1 to v2

examples/config-default-authz.json, pkg/api/authz.go, pkg/api/config/config.go, pkg/api/controller_test.go, pkg/api/routes.go, pkg/cli/root.go, pkg/cli/root_test.go
Signed-off-by: Laurentiu Niculae niculae.laurentiu1@gmail.com
[Issue #283](https://github.com/project-zot/zot/issues/283)
```release-note
```
=> storage: prevent tag overwrites controlled via configuration

go.mod, go.sum, golangcilint.yaml
https://github.com/project-zot/zot/security/dependabot/14
bug
https://github.com/project-zot/zot/security/dependabot/14
Fixes a medium CVE
=> dependabot alert: fix CVE-2022-29810

CODEOWNERS
documentation
Adds a CODEOWNER to automatically route PRs.
=> add a CODEOWNERS file

pkg/cli/extensions_test.go
Closes #508
This PR fixes issue #508 
=> use TempDir instead of /tmp/zot in tests

cmd/zb/main.go
=> zb: fix usage help output

stacker-conformance.yaml, stacker-zb.yaml, stacker-zxp.yaml, stacker.yaml
cleanup
uses a lightweight base image, previously centos
=> stacker builds: use a different base image

pkg/api/config/config.go, pkg/api/controller.go, pkg/cli/root.go, pkg/cli/root_test.go
=> Report unknown keys when parsing configuration files

.github/workflows/cluster.yaml
=> clustering: Give time to minio container to come up

pkg/api/routes.go, pkg/api/routes_test.go
Issue #492
Closes #492
Raise cod coverage for routes.go
```release-note
```
=> Adding mocked tests for routes

stacker-conformance.yaml, stacker-zb.yaml, stacker-zxp.yaml, stacker.yaml
bug
we use alpine as a base container image so also need to include a compatible runtime so that our pie-mode binaries can run.
=> fix stacker build file to include compatible glibc runtime

go.mod, go.sum, golangcilint.yaml
bug
https://github.com/project-zot/zot/security/dependabot/15
security fix
=>   fix CVE-2022-29162/GHSA-f3fp-gc8g-vw66 

.github/workflows/cluster.yaml, cmd/zb/README.md, cmd/zb/main.go, cmd/zb/perf.go
=> zb: pick client IPs from a pool, closes #472

pkg/log/log_test.go, pkg/storage/storage_fs_test.go
added tests to increase code coverage
```release-note
```
=> Code coverage improvement

.github/workflows/ci-cd.yml, stacker-conformance.yaml, stacker-zb.yaml, stacker-zxp.yaml, stacker.yaml
=> ci/cd: Fix arm builds

go.sum, pkg/cli/service.go
=> zli: cve scan doesn't print CRITICAL vulnerabilities for image

pkg/extensions/search/common/common_test.go, pkg/extensions/search/common/oci_layout.go
expanded repo info also provides information if manifests of repo is signed or not
previously it was looking for only cosign signature.
=> check notary v2 signature while looking for available signatures

pkg/extensions/sync/sync_test.go
test added
Ensure that ORAS artifacts can be synced
=> Added sync onDemand test for ORAS artifact

pkg/extensions/search/search.md
=> fix sample request url in search extension README

pkg/api/constants/consts.go, pkg/api/controller_test.go, pkg/api/routes.go, pkg/test/common.go
=> routes: strip query parameter from request URL 

pkg/extensions/sync/on_demand.go, pkg/extensions/sync/signatures.go, pkg/extensions/sync/sync.go, pkg/extensions/sync/utils.go
Signed-off-by: Catalin Hofnar <catalin.hofnar@gmail.com>
enhancement
#336 
This PR adds a type evaluation function in utils.go so that we can also print the type of the error, not just its message. Also modified every log.error call to use this function.
The user will now be able to see the type of the error in the logs.
Example:
From:
```
{"level":"error","error":"open /invalid/path/to/file: no such file or directory","goroutine":68,"caller":"/home/chofnar/go/src/github.com/project-zot/zot/pkg/extensions/sync/sync.go:543","time":"2022-04-15T17:45:33.8741831+03:00","message":"couldn't get registry credentials from …
```
=> Modified sync error log calls to include error type

.github/workflows/sync-golang-image.yaml
```release-note
```
closes #585
=> Periodically sync golang image from dockerhub to ghcr.io

cmd/zb/helper.go, cmd/zb/perf.go
=> zb: replace map with sync.Map to avoid concurrent writes closes #582

.github/workflows/cluster.yaml, .github/workflows/ecosystem-tools.yaml, pkg/extensions/sync/sync_test.go, test/blackbox/pushpull.bats, test/blackbox/sync.bats
=> ci/cd: fix oras cli flags after it got updated

SECURITY.md
documentation
Adds a security policy document to address recently found security vulnerabilities.
```release-note
```
=> add a security policy document

.github/workflows/ci-cd.yml
=> Rename push token

.github/dependabot.yml
bug
.github/depedabot.yml is incorrect.
```release-note
```
=> fix dependabot.yml

.github/workflows/benchmark.yaml, .github/workflows/ci-cd.yml, .github/workflows/cloc.yml, .github/workflows/cluster.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/dco.yml, .github/workflows/ecosystem-tools.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/license.yaml, .github/workflows/oci-conformance-action.yml, .github/workflows/scorecards.yml, .github/workflows/stale.yaml, .github/workflows/tls.yaml
cleanup
fix issues as reported by dependabot
```release-note
```
=> fix dependabot alerts

.github/workflows/ci-cd.yml, .github/workflows/codeql-analysis.yml, .github/workflows/ecosystem-tools.yaml, .github/workflows/oci-conformance-action.yml, .github/workflows/stale.yaml, .github/workflows/sync-golang-image.yaml
cleanup
OSSF scorecard github workflow hardening
```release-note
```
=> harden github action/workflow perms

.github/workflows/branch-cov.yml
feature
https://github.com/project-zot/zot/issues/644
Reports branch coverage so that we can improve our unit tests
```release-note
```
=> add a github workflow to report branch coverage

pkg/cli/stress_test.go
cleanup
pkg/cli/stress_test.go fails on all PRs
- Decrease RLIMIT_NOFILE and the number of goroutines used to reach this limit (from 512 to 100)
- Reset RLIMIT_NOFILE to the initial value before the test finishes
- Remove panic
- Use temporary dir managed by test framework
- Swith to using test logging in pkg/cli/stress_test.go
- Execute commands without `bash -c` in pkg/cli/stress_test.go
First item is needed as the GH runner seems to stop the test if stressed too much.
The lower number is still good enough to reproduce the test conditions
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Fixes/Improvements to pkg/cli/stress_test.go

.github/workflows/stale.yaml, .github/workflows/sync-golang-image.yaml
repo automation
Fix errors such as:
- https://github.com/project-zot/zot/actions/runs/2740010552
- https://github.com/project-zot/zot/actions/runs/2736838219
=> Fix typos in workflow permissions

Makefile, test/blackbox/helpers_pushpull.bash, test/blackbox/pushpull.bats
=> regclient blackbox tests and regclient installation in Makefile

.gitignore
To avoid committing it in the future
=> Add the hack folder to .gitignore

.github/workflows/ecosystem-tools.yaml, pkg/api/controller_test.go, pkg/storage/local.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go, test/blackbox/pushpull.bats
feature
https://github.com/project-zot/zot/issues/640
Adds support for OCI image index at manifest endpoint.
```release-note
```
=> support OCI image index at manifest endpoint

test/blackbox/pushpull.bats
=> fix chart version from pushpull.bats

LICENSE, NOTICE
documentation
adds a copyright notice
=> add a copyright notice

.github/workflows/ci-cd.yml
bug
Looks like artifact upload is broken.
=> fix artifact upload action in github workflow

Makefile, pkg/api/authz.go, pkg/api/controller_test.go, test/scripts/gen_nameless_certs.sh
bug
resolves: #614
Username unknown in case of certificates authentication. This PR solves the issue
```release-note
```
=> Get identity from certificate when using mTLS

Makefile
=> fix `make binary-stacker` Makefile target

.github/workflows/benchmark.yaml, .github/workflows/cluster.yaml
=> Fix syntax errors in benchmark and cluster workflows

pkg/cli/extensions_test.go
Closes #766
```release-note
```
=> Read log path and verify content separately to avoid failed tests

pkg/storage/cache.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go
s3: fix dedupe failing to manage blobs correctly
in order to know which blob is 'real' (has content) we need to know which was the first blob inserted in cache, because that is always the real one.
because we can not modify the keys order in boltdb we'll do this by marking the first blob inserted with a value
when GetBlob() return the blob which is marked
when PutBlob() if is the first one, mark it
when DeleteBlob() in case deleted is marked then mark the next blob
**Will this break …
=> s3: fix dedupe failing to manage blobs correctly

go.mod, go.sum
dependencies
https://artifacthub.io/packages/helm/zot/zot?modal=security-report
=> fix security alerts from artifacthub

pkg/storage/cache.go, pkg/storage/local_test.go
Under digest bucket create 2 buckets, one for storing origin blob and one for storing deduped blobs.
PutBlob() - puts an origin blob in both buckets
- puts a deduped blob in deduped bucket
GetBlob() - returns blobs only from origin bucket
DeleteBlob() - deletes an origin blob from both buckets
and moves one deduped blob into origin bucket
- deletes a deduped blob from deduped bucket
[storage] When deleting an origin blob, next time we GetBlob() we get a deduped blob with no content and we will move the content from the deleted origin blob to it. …
=> Refactor s3 dedupe

errors/errors.go, pkg/api/controller_test.go, pkg/api/routes.go, pkg/storage/cache.go, pkg/storage/local.go, pkg/storage/local_test.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go, pkg/storage/storage.go, pkg/test/mocks/image_store_mock.go
feature
issue #762 
As per dist-spec, resumable pulls should be supported. Common tools in the container ecosystem don't use this. But per issue #762, some tools do require it.
No.
=> routes: support resumable pull

README.md
documentation
none
updates the README to advertise key features.
=> update README.md for release

pkg/extensions/search/common/common.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/common/oci_layout.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/gql_generated/models_gen.go, pkg/extensions/search/resolver.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go
Description, Labels, Licenses, Title, Documentation, Source
closes #786
```release-note
```
=> graphql: Populate ImageSummary missing fields:

README.md
documentation
Updates the original presentation (which was archived) link
=> update presentation links

pkg/extensions/search/common/common_test.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/gql_generated/models_gen.go, pkg/extensions/search/resolver.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go
feature
it adds information regarding command history of an image
Closing https://github.com/project-zot/zot/issues/748
=> update ImageSummary to return the history of an image

pkg/cli/image_cmd.go, pkg/cli/image_cmd_test.go, pkg/cli/searcher.go, pkg/cli/service.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/common/oci_layout.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go, pkg/test/mocks/oci_mock.go
Basically https://github.com/project-zot/zot/pull/732 plus a minor fix for one of the tests.
Credit goes to @aokirisaki.
=> list all images that have all layers of the base image included (2)

pkg/cli/client.go
So that it works with proxy settings.
bug.
zli currently is unable to connect to zot servers behind HTTP proxies.
=> zli: fix http client transport

pkg/cli/image_cmd.go, pkg/cli/image_cmd_test.go, pkg/cli/searcher.go, pkg/cli/service.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go
=> list all images that have are derived from the given image

pkg/cli/client.go, pkg/cli/cve_cmd.go, pkg/cli/cve_cmd_test.go, pkg/cli/image_cmd.go, pkg/cli/image_cmd_test.go, pkg/cli/repo_cmd.go, pkg/cli/searcher.go, pkg/cli/service.go
=> add debug flag for zli commands

pkg/log/log.go
=> Fix logger race condition

.github/workflows/sync-golang-image.yaml
ci/cd helper
golang version 1.19 has been released. Make that option available for zot builds.
=> also sync golang 1.19

examples/config-allextensions.json, examples/config-scrub.json, pkg/cli/extensions_test.go, pkg/cli/root.go, pkg/extensions/config/config.go, pkg/extensions/extension_scrub.go, pkg/extensions/scrub/scrub_test.go, test/blackbox/scrub.bats
=> Add enable/disable option for scrub extension

README.md
documentation
updates README.md to add sponsors info
=> add sponsors info

pkg/extensions/extension_metrics.go, pkg/extensions/extension_search.go, pkg/extensions/sync/sync.go
- no longer needed, the race conditions were fixed
cleanup
We are cleaning the forks made to the logger because they are no longer needed. Issue with race condition fixed in #817 
```release-note
```
=> Remove forking logger

.github/workflows/commit-msg.yaml
ci/cd feature
ci/cd pipeline enhancement to check for sane commit msgs.
=> style(ci/cd): add a commit msg style checker

.github/workflows/commit-msg.yaml
Update the checker to check for length limits and against all commits.
bug
update the ci/cd checker
=> fix(ci/cd): update the commit msg checker settings

pkg/cli/root.go, pkg/cli/root_test.go, pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_test.go
Added an end to end test for this feature, closes #793
```release-note
```
=> fix(sync): revert code which removed image destination feature

pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_internal_test.go, pkg/extensions/sync/sync_test.go, pkg/extensions/sync/utils.go
=> fix(sync): also sync image index mediatype

pkg/cli/root_test.go
Should help with test flakiness
(the order in which the policies are read from the map impacted tested codepath)
test
Test flakiness
=> test(authz): add an extra test for authz

pkg/cli/client.go, pkg/cli/image_cmd_test.go, pkg/cli/searcher.go, pkg/cli/service.go
=> fix: images command not truncating image name/tag 

pkg/storage/local/local.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go
=> fix(storage): resolve cache/storage inconsistencies on HEAD request

.github/workflows/ci-cd.yml, stacker.yaml
Fix typo in the workflow.
Pass RELEASE_TAG env var.
bug
bug in ci/cd workflow
=> ci: fix image build/release workflow

pkg/api/controller_test.go, pkg/api/routes_test.go, pkg/extensions/search/common/common_test.go, pkg/test/common.go
cleanup
Removes hardcoded digests where possible
=> refactor(tests): remove hardcoded digests

pkg/api/authz.go, pkg/api/constants/extensions.go, pkg/api/controller_test.go, pkg/api/session.go, pkg/cli/cve_cmd.go, pkg/cli/cve_cmd_test.go, pkg/cli/image_cmd_test.go, pkg/cli/service.go, pkg/debug/gqlplayground/gqlplayground.go, pkg/extensions/extension_search.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/digest/digest_test.go
=> chore: rename search route prefix

pkg/api/routes_test.go, pkg/test/common_test.go
#889 
reduce tests coverage flakiness
=> fix(tests): consolidate routes tests

pkg/cli/cve_cmd_test.go, pkg/cli/image_cmd_test.go, pkg/cli/searcher.go, pkg/cli/service.go, pkg/extensions/search/resolver.go
=> fix: zli images show if signed instead of signature

pkg/extensions/search/cve/cve.go, pkg/extensions/search/cve/cve_test.go
Values returned now by GetCVESummaryForImage
// not scannable / error during scan  - max severity ""            - cve count 0   - Errors
// scannable no issues found          - max severity "NONE"        - cve count 0   - no Errors
// scannable issues found             - max severity from Scanner  - cve count >0  - no Errors
Before this change the max severity in cases 1 and 2 was "UNKNOWN" which is also possible value for case 3. To better distinguish them return different max severities.
This feature would be consumed by the UI, which would show (or not show) different cases. 
feature
Yes, see above.
By submitting this pull request, I confirm that my …
=> feat(cve): better distinguish max severity on an image

pkg/extensions/sync/on_demand.go, pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_test.go, pkg/extensions/sync/utils.go
=> fix(sync): also sync on demand digests, not only tags, closes #902

Makefile, test/blackbox/annotations.bats
resolves: #867 
```release-note
```
=> test: Add cosign and notations bats tests

pkg/cli/client.go, pkg/cli/image_cmd_test.go
=> bug: fixed image size not counting config and manifest sizes

go.mod, go.sum
https://github.com/project-zot/zot/pull/973
update deps
```release-note
```
=> chore(deps): fix dependabot alerts

pkg/extensions/search/common/common.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/common/model.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/gql_generated/models_gen.go, pkg/extensions/search/resolver.go, pkg/extensions/search/schema.graphql
=> ImageSummary should have author information

build/stacker-conformance.yaml, build/stacker-zb.yaml, build/stacker-zxp.yaml, build/stacker.yaml
closes #988
```release-note
```
=> fix(ci): fix releasing zot minimal image

build/stacker-conformance.yaml, build/stacker-zb.yaml, build/stacker-zxp.yaml, build/stacker.yaml
bug
https://github.com/project-zot/zot/issues/980
we fixed stacker so that it can set the right arch/os
```release-note
```
=> fix(ci): set correct arch/os for published container images

codecov.yml
Code coverage for swagger component should really be at 100%
```release-note
```
=> test(swagger): increase coverage using fault injection

README.md
Thanks @dtzar for the initial PR.
https://github.com/project-zot/zot/pull/992
documentation
https://github.com/project-zot/zot/issues/935
updates README per the issue filed.
```release-note
```
=> doc: update README with minimal image and urls

pkg/cli/client.go, pkg/cli/image_cmd_test.go
=> fix: signatures now show correctly if signed or not

Makefile, test/blackbox/sync.bats
=> test(sync): added blackbox tests for sync

pkg/api/controller.go, pkg/api/controller_test.go
We added remote cache driver support. Just adding some more hardening in case of misconfig.
```release-note
```
=> fix: handle remote cache driver misconfig

pkg/api/controller_test.go, pkg/storage/common.go, pkg/storage/common_test.go, pkg/storage/local/local.go, pkg/storage/local/local_test.go, pkg/storage/s3/s3.go
=> feat: gc untagged manifests and signatures without references

Makefile, pkg/api/controller_test.go, pkg/api/routes.go, pkg/storage/common.go, pkg/storage/common_test.go, test/blackbox/pushpull.bats
=> Upgrade oras cli

README.md, cmd/zb/README.md, cmd/zb/perf.go
cleanup
`zb` output is confusing, so cleanup and give better user feedback.
```release-note
```
=> perf(zb): cleanup tool output

.github/workflows/ecosystem-tools.yaml, examples/config-all-remote.json, examples/config-search.json, pkg/cli/extensions_test.go, pkg/cli/root.go, pkg/cli/root_test.go, test/blackbox/cloud-only.bats
Fixes https://github.com/project-zot/zot/pull/1017
```release-note
```
=> fix(config): warn if cve is used with remote storage driver 

.github/workflows/cluster.yaml, .github/workflows/codeql-analysis.yml
=> ci: remove superfluous parts of github workflows

pkg/api/controller_test.go, pkg/api/routes_test.go, pkg/test/common.go
=> refactor: Cleanup/simplify test cases

pkg/api/controller_test.go
=> refactor: Cleanup/simplify tests: uploads

.github/workflows/ci-cd.yml
=> ci: start localstack container only if needed

errors/errors.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/schema.resolvers.go
=> fix: error message when CVE search is disabled

MAINTAINERS.md
=> docs: fix CNCF related documentation

.gitignore
Signed-off-by: Ravi Chamarthy <ravchama@cisco.com>
Updating .gitignore
None
It adds stacker files to gitignore so that dirty stacker files are ignored.
NA
NA
NA
No
=> fix: add stacker to .gitignore

pkg/cli/searcher.go
=> fix: added error message for missing CVEs

.github/workflows/sync-3rdparty-images.yaml
=> fix(ci): fix path to trivy-db copy under project-zot

.github/workflows/sync-3rdparty-images.yaml, Makefile
=> ci: also allow manual workflow triggers

errors/errors.go, pkg/meta/repodb/dynamodb-wrapper/dynamo_internal_test.go, pkg/meta/repodb/dynamodb-wrapper/dynamo_test.go, pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go, pkg/meta/repodb/repodb_test.go
ci
Flakiness in tests run for https://github.com/project-zot/zot/pull/1107
Creating/Deleting DynamoDB tables is async, for reliability wait for the operation to finish.
Also the tests run for DynamoDB may use the same table names concurrently.
=> Fixes for DynamoDB driver tests

pkg/cli/client_elevated_test.go, pkg/cli/client_test.go, pkg/cli/image_cmd_test.go, pkg/cli/root_test.go, pkg/cli/stress_test.go
=> refactor: Cleanup/simplify testcases in /pkg/cli

LICENSE, NOTICE
https://github.com/cncf/toc/issues/972
```release-note
```
=> docs: fix copyright related info for cncf onboarding

pkg/cli/cve_cmd_test.go, pkg/cli/extensions_test.go, pkg/extensions/config/config.go, pkg/extensions/extension_search.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/cve/cve.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/trivy/scanner.go, pkg/extensions/search/cve/trivy/scanner_internal_test.go
=> Test downloading trivy-db from alternate location

pkg/extensions/extensions_test.go, pkg/extensions/lint/lint_test.go, pkg/extensions/monitoring/monitoring_test.go, pkg/extensions/scrub/scrub_test.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/digest/digest_test.go, pkg/extensions/sync/sync_disabled_test.go, pkg/extensions/sync/sync_internal_test.go, pkg/extensions/sync/sync_test.go, pkg/test/common.go, pkg/test/common_test.go
=> refactor: Cleanup/simplify testcases in /pkg/extensions

pkg/api/controller_test.go, pkg/cli/client_test.go, pkg/cli/cve_cmd_test.go, pkg/cli/image_cmd_test.go, pkg/common/common_test.go, pkg/compliance/v1_0_0/check.go, pkg/log/log_test.go, pkg/storage/local/local_test.go, pkg/test/common_test.go
=> test(refactor): cleanup/simplify testcases

pkg/extensions/search/cve/cve.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/trivy/scanner.go, pkg/extensions/search/cve/trivy/scanner_internal_test.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/resolver.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go, pkg/test/mocks/cve_mock.go
=> feat(cve): the cve related calls to use repodb and add pagination on image results

.github/workflows/ci-cd.yml, pkg/cli/image_cmd_test.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/convert/convert_test.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/resolver.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go
=> feat(repodb): implement pagination for ImageList and integrate it with RepoDB

pkg/extensions/search/cve/cve.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/pagination.go, pkg/extensions/search/cve/pagination_test.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/gql_generated/models_gen.go, pkg/extensions/search/resolver.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go, pkg/test/mocks/cve_mock.go
=> feat(cve): graphql: paginate returned CVEs for a given image

pkg/api/controller_test.go, pkg/api/routes.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/resolver.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go, pkg/extensions/sync/signatures.go, pkg/storage/common.go, pkg/storage/common_test.go, pkg/storage/local/local.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go, pkg/storage/storage.go, pkg/test/mocks/image_store_mock.go
=> fix(referrers): fix some conformance issues

pkg/exporter/cli/cli_test.go
=> test(exporter): add unit test to cover cli pkg

.github/workflows/gqlgen.yaml, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/gql_generated/models_gen.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/search.md
Signed-off-by: Catalin Hofnar <catalin.hofnar@gmail.com>
(cherry picked from commit 2268fa0510b32b27f2c1f71e9889ec769877553b)
Resolves #952 
=> docs(graphql): rewrote search.md

pkg/cli/cve_cmd_test.go
cli tests: remove redundant conveys in CVE tests
cli tests: reduce duration of CVE tests by reducing the number of DB downloads
=> test: refactor CVE tests in CLI package

Makefile
=> test: show the execution times of the tests

.github/workflows/ci-cd.yml, .gitignore, Makefile, build/stacker.yaml, examples/config-ui.json, pkg/api/routes.go, pkg/cli/extensions_test.go, pkg/debug/gqlplayground/gqlplayground.go, pkg/debug/swagger/swagger.go, pkg/debug/swagger/swagger_disabled.go, pkg/extensions/config/config.go, pkg/extensions/extension-ui-disabled.go, pkg/extensions/extension-ui.go, pkg/extensions/extension_metrics.go, pkg/extensions/extension_metrics_disabled.go, pkg/extensions/extension_search.go
Include https://github.com/project-zot/zui in the zot binary
(cherry picked from commit d557da0baba819b7cd7e6b5941528776e125ac6d)
build(ui): fix stacker builds
(cherry picked from commit ba25daf02b4a9bc7ee1cb6f84b7a6b096ca7d61f)
build(ui): various fixes
- Fix metrics endpoint
- Fix unit tests unit tests
- Make the ui build optional in the makefile before the linter lint runs in the golangci-lint workflow
- Do not attempt to include UI routes if search is enabled
- Fix authorization for search endpoint
fix: use zot tag in ui make target
Signed-off-by: Catalin Hofnar <catalin.hofnar@gmail.com>
(cherry picked from commit …
=> feat(ui): package zui within zot binary

pkg/api/routes.go
bug + feature
none that i know of
make sure on-demand always sync the manifest, so when pulling images such as:  
`docker pull my-zot-repo-host:5000/docker.io.mirror.on-demand/alpine:latest`
will actually get the latest manifest all the time and not the cached manifest
this is expected behavior from a client perspective  
this will also allow to use "on-demand" in conjunction with poll-interval, making sure the poll interval syncs the blobs and when a client asks for an image, on-demand will make sure it got the latest manifest and downloaded unsynced blobs if needed
=> onDemand check for updated manifest

.github/workflows/ci-cd.yml, Makefile
=> feat(ui): use a Makefile variable to download a pre-existing zui build

examples/config-multiple-cve.json, pkg/cli/root.go, pkg/cli/root_test.go
=> fix: set GC delay defaults for storage subPaths

pkg/cli/image_cmd_test.go, pkg/cli/searcher.go, pkg/cli/service.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/digest/digest_test.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/resolver.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go, pkg/extensions/search/search.md, test/blackbox/annotations.bats
Closes #1166 
```release-note
```
=> perf: update the ImageList queries to return PaginatedImagesResult

pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
=> feat(scheduler): use an worker pool for scheduler

pkg/extensions/config/config.go, pkg/extensions/config/sync/config.go, pkg/extensions/extensions_test.go, pkg/extensions/sync/on_demand.go, pkg/extensions/sync/signatures.go, pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_disabled_test.go, pkg/extensions/sync/sync_internal_test.go, pkg/extensions/sync/sync_test.go, pkg/extensions/sync/utils.go
=> Centralise extensions config entries

.github/workflows/sync-3rdparty-images.yaml
=> chore: add/sync golang 1.20.x images

.github/workflows/sync-3rdparty-images.yaml
Since the matrix values were unquoted,
the logic reading the yaml considered them numbers
=> ci(golang): fix syncing build image golang 1.20

pkg/api/controller.go, pkg/extensions/extension_search.go, pkg/extensions/extension_search_disabled.go, pkg/extensions/search/cve/cve_test.go
=> fix: trivydb update now uses task scheduler

examples/README.md
=> feat(doc): add documentation for dynamodb

errors/errors.go, pkg/api/controller.go, pkg/api/routes.go, pkg/extensions/extension_sync.go, pkg/extensions/extension_sync_disabled.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/convert/convert_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/pagination_test.go, pkg/extensions/search/cve/trivy/scanner_internal_test.go, pkg/extensions/search/resolver_test.go, pkg/extensions/sync/on_demand.go, pkg/extensions/sync/signatures.go, pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_internal_test.go, pkg/extensions/sync/sync_test.go, pkg/extensions/sync/utils.go, pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go, pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper_test.go, pkg/meta/repodb/common/common.go, pkg/meta/repodb/dynamodb-wrapper/dynamo_test.go, pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go, pkg/meta/repodb/repodb.go, pkg/meta/repodb/repodb_test.go, pkg/meta/repodb/sync_repodb.go, pkg/meta/repodb/sync_repodb_test.go, pkg/meta/repodb/update/update.go, pkg/meta/repodb/update/update_test.go, pkg/test/common_test.go, pkg/test/mocks/repo_db_mock.go
=> feat(repodb): update repodb after sync operation

go.mod
=> chore(deps): modify pkg/errors dependency as indirect

pkg/api/authn.go, pkg/api/controller_test.go, pkg/extensions/extensions_test.go, pkg/test/bearer.go, pkg/test/common_test.go
=> fix(mgmt): skip bearer authn for mgmt route

pkg/extensions/lint/lint.go
=> fix(errors): remove direct dependency on 'github.com/pkg/errors'

pkg/cli/client.go, pkg/cli/client_utils_test.go, pkg/cli/cve_cmd_test.go, pkg/cli/image_cmd_test.go, pkg/cli/service.go, pkg/extensions/search/common/common_test.go, pkg/extensions/search/common/model.go, pkg/extensions/search/convert/convert_test.go, pkg/extensions/search/convert/repodb.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/gql_generated/models_gen.go, pkg/extensions/search/schema.graphql
Feature
This PR updates the way the CLI displays multi-arch images
```release-note
```
=> feat(cli): updated display format for multiarch images

test/blackbox/cve.bats
=> fix(cve): blackbox cve tests now verifying actual cves

pkg/meta/common/common.go, pkg/meta/common/common_test.go, pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go, pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go
bug
There was a miscalculator of the repoLastUpdated value when searching for repos in RepoDB.
```release-note
```
=> fix(repodb): fixed assigned repoLastUpdated when searching for repos

.github/workflows/scorecards.yml, go.mod, go.sum
=> chore(go.mod): fix dependabot alerts

pkg/extensions/sync/sync_internal_test.go, pkg/extensions/sync/sync_test.go, pkg/extensions/sync/utils.go
=> test(sync): consolidate all sync tests

.github/workflows/nightly.yaml, Makefile, errors/errors.go, pkg/api/controller.go, pkg/api/controller_test.go, pkg/common/common.go, pkg/extensions/extensions_test.go, pkg/extensions/scrub/scrub_test.go, pkg/scheduler/scheduler.go, pkg/storage/cache/boltdb.go, pkg/storage/common.go, pkg/storage/local/local.go, pkg/storage/local/local_test.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go, pkg/storage/storage.go, pkg/storage/storage_test.go, pkg/test/mocks/cache_mock.go, pkg/test/mocks/image_store_mock.go, test/blackbox/helpers_cloud.bash, test/blackbox/pushpull_running_dedupe.bats, test/blackbox/restore_s3_blobs.bats, test/blackbox/scrub.bats
closes #565
```release-note
```
=> feat(storage): rebuild s3/local dedupe index when switching dedupe status

.github/workflows/ecosystem-tools.yaml, Makefile, test/blackbox/pushpull.bats
=> test: additional blackbox tests for client push/pull

pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/gql_generated/models_gen.go, pkg/extensions/search/resolver.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/userprefs_test.go, pkg/meta/common/common.go, pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go, pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper_test.go, pkg/meta/repodb/repodb.go
Closes #974 
Closes #659
```release-note
```
=> Global search filterby bookmarked

pkg/cli/root.go
Fixes issue #1392
```release-note
```
=> fix(serve): exit with a status code on error instead of panic

build/Dockerfile, build/Dockerfile-conformance, build/Dockerfile-minimal, build/Dockerfile-zb, build/Dockerfile-zxp, build/stacker-conformance.yaml, build/stacker-minimal.yaml, build/stacker-zb.yaml, build/stacker-zxp.yaml, build/stacker.yaml
=> fix: use golang 1.20 to build our container images

Makefile, examples/config-ui.json, pkg/cli/root.go, pkg/cli/root_test.go, pkg/extensions/extension_mgmt.go
=> feat: verifying and enabling necessary extensions for ui

Makefile
=> bug(makefile): the EXTENSIONS variable was not replaces by BUILD_LABELS in 2 places

pkg/extensions/sync/signatures.go
=> Fix sync repodb signatures

pkg/common/model.go, pkg/extensions/search/convert/repodb.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/gql_generated/models_gen.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/search_test.go
Closes #1447
```release-note
```
=> feat(search): add artifact type to manifest summary gql structure

pkg/api/constants/extensions.go, pkg/api/controller.go, pkg/api/controller_test.go, pkg/api/routes.go, pkg/extensions/extension_mgmt.go, pkg/extensions/extension_search.go, pkg/extensions/extension_userprefs.go
Closes #1454
```release-note
```
=> feat(routes): move the cors handler from /v2 to only where it's needed

.github/workflows/ci-cd.yml, .github/workflows/commit-msg.yaml, .github/workflows/nightly.yaml, .github/workflows/sync-3rdparty-images.yaml, Makefile, SECURITY.md, golangcilint.yaml
https://github.com/project-zot/zot/security/code-scanning/4293
```release-note
```
=> chore: fix security alerts

test/blackbox/cve.bats
=> fix: replaced used CVE in blackbox test

.github/workflows/cluster.yaml
=> feat(ci): give minio container more time to start

pkg/extensions/extension_userprefs.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
=> fix: removed quotation marks from enum in swagger docs

pkg/api/authn.go, pkg/api/authz.go, pkg/api/config/config.go, pkg/api/controller.go, pkg/api/controller_test.go, pkg/api/errors/errors.go, pkg/api/errors/errors_test.go, pkg/api/routes.go, pkg/common/common.go, pkg/common/common_test.go, pkg/common/http_client.go, pkg/common/http_client_test.go, pkg/common/http_server.go, pkg/common/oci.go, pkg/common/oci_test.go, pkg/extensions/search/cve/cve_test.go
cleanup
moves helper functions and their dependencies under the common package.
creates a new package under api called api/errors for evading circular imports related to importing error variables
```release-note
```
=> refactor: move helper functions under common, in usage specific named files

pkg/cli/search_cmd.go
=> fix(cli): add help message for searching referrers under search command

.github/workflows/oci-conformance-action.yml
=> fix: update conformance test

test/blackbox/sync_docker.bats
=> test: add more registries in sync blackbox tests

examples/config-popular-registries.json
No issue, only documentation to give examples for most popular public registries.
At least one image has been pulled from each registry.
N/A
No
No
```release-note
```
=> documentation: Add example for various popular public registries

.github/workflows/web-scan.yml, go.mod, go.sum
=> chore: fix dependabot alerts

pkg/api/controller.go, pkg/cli/config_reloader_test.go, pkg/extensions/search/cve/trivy/scanner.go
=> fix(test): TestConfigReloader, wait for trivy db download

.github/actions/clean-runner/action.yaml, .github/workflows/ci-cd.yml, .github/workflows/nightly.yaml, test/blackbox/helpers_sync.bash, test/blackbox/restore_s3_blobs.bats, test/blackbox/sync_harness.bats
=> fix(nightly): fix nightly builds

pkg/storage/local/local.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go
This is an alternative to https://github.com/project-zot/zot/pull/1586 but missing the conformance test update
```release-note
```
=> fix: missing Oci-Subject header pushing index with subject

pkg/storage/local/local.go, pkg/storage/s3/s3.go
We use locks to protect OCI layouts. However, our critical sections have too long and cover code instead of data.
Fixes issue #1595
```release-note
```
=> fix: refactor monitoring code outside locks

.github/workflows/oci-conformance-action.yml, cmd/zb/helper.go, errors/errors.go, pkg/api/controller_test.go, pkg/api/routes.go, pkg/storage/common/common.go, pkg/storage/local/local.go, pkg/storage/local/local_test.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go, pkg/storage/storage_test.go
=> fix: don't allow blobs to be deleted if in use

pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/resolver.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go, pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper.go, pkg/meta/repodb/boltdb-wrapper/boltdb_wrapper_test.go, pkg/meta/repodb/dynamodb-wrapper/dynamo_test.go, pkg/meta/repodb/dynamodb-wrapper/dynamo_wrapper.go, pkg/meta/repodb/repodb.go, pkg/meta/repodb/repodb_test.go, pkg/test/mocks/repo_db_mock.go
This was a request from UI side.
=> feat(cve): ability to return CVEs per image os and architecture

pkg/extensions/sync/references/oci.go, pkg/extensions/sync/references/references_internal_test.go
bug
fixing test coverage inconsistency
```release-note
```
=> fix(test): sync inconsistent test

.github/workflows/oci-conformance-action.yml, go.sum, pkg/api/controller_test.go, pkg/cli/image_cmd_test.go, pkg/cli/search_cmd_referrers_test.go, pkg/extensions/search/search_test.go, pkg/extensions/sync/sync_test.go, pkg/storage/common/common.go, pkg/storage/local/local.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go, pkg/test/common.go, pkg/test/common_test.go, test/blackbox/referrers.bats
=> feat: add additional manifest validations

pkg/cli/config_cmd.go, pkg/cli/config_cmd_test.go
https://github.com/project-zot/zot/issues/1594
- use indent '  ' in the config json
https://github.com/project-zot/zot/issues/1593
- add subcommand `zli config remove`
=> feat(zli): add new subcommand to remove a zli config

pkg/api/authn.go, pkg/api/authz.go, pkg/api/config/config.go, pkg/api/controller.go, pkg/api/controller_test.go, pkg/api/routes.go, pkg/cli/root.go, pkg/common/http_server.go, pkg/extensions/extension_api_key.go, pkg/extensions/extension_mgmt.go, pkg/extensions/extension_search.go, pkg/extensions/extension_userprefs.go
- apply Access-Control-Allow-Credentials only if authn is enabled
- enable Logout route for basic auth
- fixed Logout godoc
- fix Access-Control-Allow-Methods on Logout route
- added allowOrigin option in config example
bug
- apply Access-Control-Allow-Credentials only if authn is enabled
- enable Logout route for basic auth
- fixed Logout godoc
- fix Access-Control-Allow-Methods on Logout route
- added allowOrigin option in config example
see #1632 
**Does this PR introduce any user-facing …
=> fix(authn): fix several issues with authn, closes #1632

pkg/cli/config_reloader.go
=> feat: signal handling

pkg/api/controller_test.go, pkg/cli/image_cmd_test.go, pkg/cli/search_cmd_referrers_test.go, pkg/cli/search_cmd_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/trivy/scanner_test.go, pkg/extensions/search/digest_test.go, pkg/extensions/search/search_test.go, pkg/extensions/sync/sync_test.go, pkg/meta/meta_test.go, pkg/meta/signatures/signatures_test.go, pkg/meta/storage_parsing_test.go, pkg/test/common.go, pkg/test/common_test.go, pkg/test/images.go, pkg/test/images_test.go, pkg/test/multiarch.go
We need a better way to create test images. Since there is a large variety of image configurations I created this PR to add a Image Builder pattern
```release-note
```
=> feat(test): Simplify tests

go.mod, pkg/api/authn.go, pkg/api/controller.go, pkg/api/controller_test.go, pkg/common/http_server.go
closes: #1642
```release-note
```
=> fix(authn): session authn is skipped when anonymous policy is configured

pkg/api/controller_test.go, pkg/cli/cve_cmd_test.go, pkg/cli/image_cmd_test.go, pkg/cli/search_cmd_referrers_test.go, pkg/cli/search_cmd_test.go, pkg/compliance/v1_0_0/check.go, pkg/extensions/extension_ui_test.go, pkg/extensions/extensions_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/trivy/scanner_internal_test.go, pkg/extensions/search/cve/trivy/scanner_test.go, pkg/extensions/search/digest_test.go, pkg/extensions/search/search_test.go, pkg/extensions/search/userprefs_test.go, pkg/extensions/sync/sync_test.go, pkg/meta/meta_test.go, pkg/meta/signatures/signatures_test.go, pkg/meta/storage_parsing_test.go, pkg/meta/update_test.go, pkg/storage/s3/s3_test.go, pkg/storage/scrub_test.go, pkg/test/common.go, pkg/test/common_test.go, pkg/test/images.go, pkg/test/images_test.go, pkg/test/oci-layout/oci_layout_test.go
=> test(upload): update the new signature of the upload image function

Makefile
bug
To fix BUILD_LABELS on darwin
User can use invalid extension names and it makes sense to filter those names in Makefile before reaching zot binary
Example:
```
make binary EXTENSIONS=mgmt,apikeys,sync,ui
```
Run _make binary_ command on Mac
No
```release-note
```
=> fix: Build scripts broken on Mac

.github/workflows/gc-stress-test.yaml, examples/config-conformance.json, examples/config-gc-bench.json, pkg/api/config/config.go, pkg/api/controller.go, pkg/api/controller_test.go, pkg/cli/root.go, pkg/debug/gqlplayground/gqlplayground.go, pkg/extensions/extension_image_trust_test.go, pkg/extensions/extension_scrub.go, pkg/extensions/extension_search.go, pkg/extensions/scrub/scrub_test.go, pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_test.go, pkg/meta/signatures/signatures.go, pkg/scheduler/README.md, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/storage/common/common.go, pkg/storage/common/common_test.go, pkg/storage/constants/constants.go, pkg/storage/local/local.go, pkg/storage/local/local_test.go, test/blackbox/scrub.bats
=> fix: remove inline GC and schedule a background task instead

Makefile, build/stacker.yaml
bug
closes #1688 
manual testing
No
No
=> fix: binary-stacker Makefile target is broken

examples/README.md
documentation
none declared
fixes case in documentation
=> docs: fix apikey case

Makefile, pkg/api/controller_test.go, pkg/api/routes_test.go, pkg/cli/client_test.go, pkg/cli/cve_cmd_test.go, pkg/cli/image_cmd_test.go, pkg/cli/searcher.go, pkg/cli/service.go, pkg/common/http_client_test.go, pkg/extensions/get_extensions_disabled_test.go, pkg/extensions/lint/lint_test.go, pkg/extensions/monitoring/monitoring_test.go, pkg/extensions/scrub/scrub_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/trivy/scanner_internal_test.go, pkg/extensions/search/cve/trivy/scanner_test.go, pkg/extensions/sync/sync_internal_test.go, pkg/extensions/sync/sync_test.go, pkg/log/log_test.go, pkg/storage/common/common_test.go, pkg/storage/local/local_test.go, pkg/test/common.go, pkg/test/common_test.go, pkg/test/images.go
Closes #1664 
Closes #1665 
```release-note
```
=> test(refactor): refactor tests that use zot-test to use smaller images

pkg/meta/parse.go
=> fix(parse): lock storage while reading using image store

examples/README.md, examples/config-minimal.json, pkg/api/authn.go, pkg/api/authn_test.go, pkg/api/constants/consts.go, pkg/api/routes.go, pkg/api/routes_test.go, pkg/meta/boltdb/boltdb.go, pkg/meta/dynamodb/dynamodb.go, pkg/meta/meta_test.go, pkg/meta/types/types.go, pkg/test/mocks/repo_db_mock.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
adding api key expiration date
feature
UI needs a way to get list of API keys for the current user, added route for this.
Added option to expire API keys after a certain date.
```release-note
```
=> feat(apikey): added route to list user api keys

examples/config-minimal.json
=> fix(examples): revert examples/config-minimal.json

test/blackbox/sync_harness.bats
=> fix: nightly build

Makefile, test/blackbox/delete_images.bats
Closes #1706
```release-note
```
=> test(bats): added bats example for deleting an image

pkg/storage/common/common.go
=> fix: add manifest validation checks

pkg/api/authn.go, pkg/api/controller.go, pkg/api/routes.go, pkg/cli/root.go, pkg/common/http_client.go, pkg/common/http_client_test.go, pkg/extensions/extension_search.go, pkg/extensions/imagetrust/image_trust.go, pkg/extensions/scrub/scrub.go, pkg/extensions/scrub/scrub_test.go, pkg/extensions/sync/httpclient/client.go, pkg/extensions/sync/on_demand.go, pkg/extensions/sync/on_demand_disabled.go, pkg/extensions/sync/references/cosign.go, pkg/extensions/sync/references/oci.go, pkg/extensions/sync/references/oras.go, pkg/extensions/sync/references/references.go, pkg/extensions/sync/references/references_internal_test.go, pkg/extensions/sync/remote.go, pkg/extensions/sync/service.go, pkg/extensions/sync/sync.go, pkg/extensions/sync/sync_internal_test.go, pkg/scheduler/README.md, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/storage/common/common.go, pkg/storage/scrub.go, pkg/storage/scrub_test.go
=> feat(scheduler): pass the shutdown/reload context to running tasks

pkg/api/controller_test.go, pkg/api/routes.go, test/blackbox/pushpull.bats
Also fix additional issues:
- sorting of tags on calls without pagination parameters ('n' or 'last')
- if 'n' is 0 we should return an empty list and not error
Added tests accordingly
=> fix(api): Fix 'last' query param for <repo>/tags/list to work without param 'n'

pkg/extensions/imagetrust/cosign.go, pkg/extensions/imagetrust/image_trust.go, pkg/extensions/imagetrust/image_trust_test.go, pkg/extensions/imagetrust/notation.go, pkg/test/mocks/secrets_manager_mock.go
=> fix: add retry logic to recreate existing trustpolicy secret

pkg/extensions/imagetrust/image_trust_test.go, pkg/extensions/imagetrust/notation.go
=> fix: do not recreate trustpolicy secret if the content doesn't change

Makefile
bug
Makes possible to compile zot binary without any EXTENSIONS set. 
Size of that binary should equal size of zot minimal binary
> EXTENSIONS= make binary
Observe that makefile target fails
1. Tested binary-minimal & exporter-minimal targets
2. tested binary target with/without EXTENSIONS
No
No
=> bug: can't build zot with empty EXTENSIONS

pkg/extensions/extension_image_trust_test.go, pkg/extensions/imagetrust/image_trust.go
=> fix: change log msg for updating signatures validity

pkg/extensions/search/convert/convert_test.go, pkg/extensions/search/convert/metadb.go, pkg/test/repo.go
=> fix(convert): fix the update rule of download count for images

errors/errors.go, pkg/cli/client.go, pkg/cli/client_test.go, pkg/cli/cmdflags/flags.go, pkg/cli/cmdflags/flags_test.go, pkg/cli/config_cmd.go, pkg/cli/config_cmd_test.go, pkg/cli/cve_cmd_test.go, pkg/cli/cves_cmd.go, pkg/cli/cves_sub_cmd.go, pkg/cli/image_cmd.go, pkg/cli/image_cmd_test.go, pkg/cli/image_sub_cmd.go, pkg/cli/repo_cmd.go, pkg/cli/repo_sub_cmd.go, pkg/cli/repo_test.go, pkg/cli/search_cmd.go, pkg/cli/search_cmd_test.go, pkg/cli/search_sub_cmd.go, pkg/cli/service.go, pkg/cli/utils.go, pkg/extensions/search/cve/pagination.go, pkg/test/multiarch.go
Closes #1625
```release-note
```
=> feat(cli): add cli sort flag to subcommands

Makefile, pkg/api/routes.go, pkg/debug/constants/consts.go, pkg/debug/pprof/pprof.go, pkg/debug/pprof/pprof.md, pkg/debug/pprof/pprof_disabled.go, pkg/debug/pprof/pprof_test.go, pkg/extensions/extension_image_trust_test.go
(cherry picked from commit 56ddb70f624e7070ad0d3531d498675f9f82c664)
And added authz on top of that commit.
See also https://github.com/project-zot/zot/pull/1489
=> feat(pprof): add profiling route handler to debug runtime

.github/workflows/gc-stress-test.yaml, .github/workflows/nightly.yaml, pkg/storage/imagestore/imagestore.go, test/blackbox/restore_s3_blobs.bats, test/gc-stress/config-gc-bench-local.json, test/gc-stress/config-gc-bench-s3-localstack.json, test/gc-stress/config-gc-bench-s3-minio.json, test/gc-stress/config-gc-referrers-bench-local.json, test/gc-stress/config-gc-referrers-bench-s3-localstack.json, test/gc-stress/config-gc-referrers-bench-s3-minio.json
=> fix(ci): print zot log on failure

pkg/extensions/search/cve/scan_test.go
=> fix(tests): call ImageStore constructor with correct parameters

build/Dockerfile
feature
This PR adds cross-compilation to the Dockerfile.
Usage:
```shell
docker buildx build --platform linux/amd64 --platform linux/arm64 -f build/Dockerfile .
```
```release-note
```
=> Add cross-compile to dockerfile

.github/actions/setup-localstack/action.yaml, .github/workflows/ecosystem-tools.yaml, .github/workflows/nightly.yaml
=> ci(localstack): pin localstack python package to 2.2.0 and pull container image from ghcr

.github/actions/setup-localstack/action.yaml
=> fix(nightly): create bucket for s3 testing with localstack

pkg/api/controller_test.go, pkg/cli/client/client.go, pkg/cli/client/utils.go, pkg/extensions/extension_image_trust_test.go, pkg/extensions/imagetrust/image_trust_test.go, pkg/extensions/sync/sync_test.go, pkg/meta/dynamodb/dynamodb_internal_test.go, pkg/meta/dynamodb/dynamodb_test.go, pkg/meta/meta_test.go, pkg/meta/parse_test.go, pkg/meta/version/version_test.go, pkg/storage/cache/dynamodb_test.go, pkg/storage/s3/s3_test.go, pkg/storage/scrub_test.go, pkg/storage/storage_test.go, pkg/test/skip/testskip.go
=> fix: running tests locally fails

pkg/meta/boltdb/boltdb.go, pkg/meta/convert/convert.go, pkg/meta/dynamodb/dynamodb.go, pkg/meta/meta_test.go
=> fix(metadb): fix unexpected panic when dereferencing map fields

pkg/extensions/search/convert/metadb.go, pkg/extensions/search/search_test.go, pkg/meta/boltdb/boltdb.go, pkg/meta/common/common.go, pkg/meta/dynamodb/dynamodb.go
=> test(meta): add push-pull-read tests for metadb

pkg/extensions/search/search.md
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 licen
=> docs: update graphql examples to match current implementation

.github/workflows/nightly.yaml
clean runner before running build
```release-note
```
=> fix(nightly): fix docker images build 'no space left on device'

test/blackbox/cve.bats, test/blackbox/helpers_zot.bash
=> test(bats): fix CVE bats test failure if zot runs on different port than 8080

pkg/meta/common/common.go, pkg/meta/convert/convert_test.go, pkg/meta/meta_test.go
=> fix(metadb): set LastUpdated field also for indexes

pkg/extensions/sync/references/references.go, pkg/storage/imagestore/imagestore.go
=> fix(log): trimmed error level logs

pkg/api/controller_test.go, pkg/api/routes.go, pkg/compliance/v1_0_0/check.go
=> feat(pagination): make sure the URL to in the link header is inside angle brackets

pkg/storage/common/common.go, test/blackbox/restore_s3_blobs.bats, test/blackbox/sync_harness.bats
=> ci(nightly): fix nightly after log message refactor

README.md
=> docs: update docs website url

pkg/exporter/api/controller_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
resolves https://github.com/project-zot/zot/issues/2155
=> fix: high CPU utilization by scheduler while idle

THIRD-PARTY-LICENSES.md, go.mod, go.sum, pkg/api/controller.go, pkg/api/controller_test.go, pkg/api/recovery.go
=> feat(log): print traceback when panics occur

pkg/api/controller_test.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/trivy/scanner_internal_test.go, pkg/extensions/search/cve/trivy/scanner_test.go, pkg/meta/parse_test.go, pkg/storage/s3/s3_test.go, pkg/storage/scrub_test.go, pkg/storage/storage_test.go, pkg/test/deprecated/deprecated.go
- update cve tests
- update scrub tests
- update tests for parsing storage and loading into meta DB
- update controller tests
=> refactor: update tests to use the newer API for creating test images

pkg/extensions/scrub/scrub_test.go, pkg/storage/scrub.go, pkg/storage/scrub_test.go
=> fix(scrub): hold locks per image not per repo while executing scrub

pkg/extensions/search/resolver.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/search_test.go
Syntax to search for `<tag_name>` accross all repos is `:<tag_name>`
=> feat(search): search for a specific tag cross-repo

pkg/extensions/sync/sync_test.go
=> fix(tests): fixed inconsistent sync test

pkg/cli/client/gql_queries.go, pkg/extensions/search/cve/cve.go, pkg/extensions/search/cve/cve_test.go, pkg/extensions/search/cve/pagination_test.go, pkg/extensions/search/gql_generated/generated.go, pkg/extensions/search/resolver.go, pkg/extensions/search/resolver_test.go, pkg/extensions/search/schema.graphql, pkg/extensions/search/schema.resolvers.go, pkg/test/mocks/cve_mock.go
=> feat(graphql): filter CVEs by severity

pkg/extensions/search/convert/annotations.go, pkg/extensions/search/convert/convert_test.go, pkg/extensions/search/convert/metadb.go
Fallback to Created field and the History entries in the image config only if the annotation "org.opencontainers.image.created" is not available
closes #2210
=> feat: Get the image LastUpdated timestamp from annotations

test/images/README.md, test/images/stacker-java.yaml, test/images/stacker-spring.yaml, test/images/test.java
=> test: add test images build instructions and stacker.yamls

pkg/api/authn_test.go, pkg/api/cookiestore.go
Refactor and add more coverage to test flacky coverage in case sessions which are already deleted are flagged as expired/for deletion.
See coverage drop in pkg/api/cookiestore.go:
https://app.codecov.io/gh/project-zot/zot/commit/8e68255946e745b872cc58ecd0899fd766bc1139/indirect-changes
=> test: fix flacky coverage in cookiestore cleanup tests

pkg/extensions/sync/destination.go, pkg/extensions/sync/service.go, pkg/extensions/sync/sync.go
cleanup blob after each sync.copyBlob()
```release-note
```
=> fix(sync): better blobs cleanup

pkg/api/routes.go
The issue was reported on Slack.
=> fix: Allow GET requests on repositories not found in metadb

.github/actions/setup-localstack/action.yaml, .github/workflows/ecosystem-tools.yaml, .github/workflows/nightly.yaml, .github/workflows/sync-3rdparty-images.yaml
There are performance improvements in recent releases of localstack.
```release-note
```
=> ci: upgrade localstack to v3.3.0

THIRD-PARTY-LICENSES.md, scripts/update_licenses.sh
misc
update_licenses.sh is slow
On a Mac M1, the total execution time goes down from 12:37 to 4:51
```
./scripts/update_licenses.sh  1138.82s user 109.82s system 164% cpu 12:37.23 total
./scripts/update_licenses.sh  1394.44s user 209.08s system 550% cpu 4:51.27 total
```
```release-note
```
=> misc: make update_licenses.sh faster

.github/workflows/test.yaml
This test is running into timing issues in our CI.
```release-note
```
=> ci: use more cores for the extensions test

go.mod, pkg/cli/client/server_info_cmd.go, pkg/cli/client/service.go
Fix outdated pkgs reported in issue #2522
```release-note
```
=> chore: update go.mod deps

.github/workflows/cluster.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/gqlgen.yaml, .github/workflows/nightly.yaml, .github/workflows/test.yaml, .github/workflows/web-scan.yaml
=> ci: stop using the non-free 4-core runners

pkg/storage/imagestore/imagestore.go
Exit early in case of all folders and known non-blob file names. This avoids the logic for validating digests, and log message generation.
=> chore: reduce number of spurious log messages produced by GetNextDigestWithBlobPaths

test/blackbox/helpers_wait.bash
=> chore: fix search for 'no digests left, finished' in nightly job

go.mod, go.sum, pkg/extensions/imagetrust/notation.go
=> build(deps): bump github.com/notaryproject/notation-go from 1.1.1 to 1.2.1

test/blackbox/pushpull_running_dedupe.bats
oras verion upgrade has incompatible cmdline args
```release-note
```
=> ci: fix nightly runs

.github/workflows/publish.yaml
=> ci: stacker runs best on ubuntu-22.04

.github/workflows/ecosystem-tools.yaml, test/blackbox/annotations.bats
=> ci: reenable test calling stacker

examples/README.md, examples/config-all-remote.json, examples/config-dynamodb.json, test/gc-stress/config-gc-bench-s3-localstack.json, test/gc-stress/config-gc-bench-s3-minio.json, test/gc-stress/config-gc-referrers-bench-s3-localstack.json, test/gc-stress/config-gc-referrers-bench-s3-minio.json
Note DeleteTable is only used for the zot tests, should not be needed in production
=> fix: Update AWS DynamoDB permission list and correct issues in DynamoDB examples

.github/workflows/benchmark.yaml, .github/workflows/cluster.yaml, .github/workflows/gc-stress-test.yaml, cmd/zb/helper.go, cmd/zb/perf.go, pkg/api/config/redis/redis.go, pkg/api/config/redis/redis_test.go
=> Cumulative improvements for CI troubleshooting

.github/workflows/ecosystem-tools.yaml, .github/workflows/nightly.yaml, Makefile, test/scale-out/cloud_scale_out_redis.bats, test/scale-out/cloud_scale_out_redis_scale.bats, test/scale-out/helpers_redis.bash, test/scale-out/helpers_zot.bash
=> test: add scale-out clustering tests using multiple zot servers with redis and S3 integration

.github/workflows/nightly.yaml, test/scale-out/cloud_scale_out_basic_auth_tls_scale.bats
- fix log folder names used by nightly jobs
- fix attempt to install containerd.io in the redis pipeline (which conflicts with containerd)
=> ci: fix failures in nightly

.github/workflows/build.yaml, Makefile, pkg/api/controller.go, pkg/api/runtime.go, pkg/api/runtime_windows.go
Currently zot project doesn't build and ship Windows binaries. This PR adds that support.
```release-note
```
=> feat: build windows binaries

pkg/api/ldap.go
feature
#3050 
Enhance LDAP user group retrieval to handle multiple attributes
No
```release-note
```
=> feat: handle multiple attributes

.github/workflows/sync-3rdparty-images.yaml
=> ci: update golang version to be synced to gh

pkg/meta/redis/redis.go
=> fix: remove unneeded double locks in redis implementation of metadb

LICENSE
=> fix: license copyright update

pkg/extensions/config/events/config.go, pkg/extensions/events/http_sink.go, pkg/extensions/events/http_sink_test.go
fixes issue #3187
```release-note
```
=> feat: add token auth support for event sink

pkg/api/config/config.go, pkg/cli/server/root.go, pkg/retention/retention.go, pkg/storage/gc/gc_test.go
=> feat: GC to cleanup untagged manifests by default

pkg/extensions/sync/sync_internal_test.go, pkg/storage/local/driver.go, pkg/storage/local/driver_test.go
=> ci: more sync/local driver tests to stabilize/increase coverage

.github/workflows/stale.yaml
=> ci: fix stale check

.github/workflows/ecosystem-tools.yaml, Makefile, test/blackbox/annotations.bats, test/blackbox/sync.bats, test/blackbox/sync_cloud.bats
=> ci: move workflow to oci runner

pkg/storage/local/local_test.go
https://app.codecov.io/gh/project-zot/zot/commit/636a6b1820088c4334b02ef5d2e61a3450c4b231/indirect-changes
=> chore: stabilize coverage for specific imagestore case

test/blackbox/sync_harness.bats
=> ci: fix nightly
